// Offline QR deep links.
//
// A QR code carries a plain local identifier, never a URL to a server:
//   to://<projectId>/checkin/<participantId>
//   to://<projectId>/match/<matchId>
//   to://<projectId>/station/<resourceId>
// Scanning opens the desktop app on exactly that screen. Parsing and resolution
// are pure so the behaviour can be tested without a camera.

export type DeepLinkKind = 'checkin' | 'match' | 'station';

export interface DeepLink {
  projectId: string;
  kind: DeepLinkKind;
  id: string;
}

export const DEEP_LINK_SCHEME = 'to://';

const KINDS: DeepLinkKind[] = ['checkin', 'match', 'station'];

export function formatDeepLink(link: DeepLink): string {
  return `${DEEP_LINK_SCHEME}${link.projectId}/${link.kind}/${link.id}`;
}

export type ParsedLink = { ok: true; link: DeepLink } | { ok: false; error: string };

export function parseDeepLink(text: string): ParsedLink {
  const raw = (text ?? '').trim();
  if (!raw) return { ok: false, error: 'This QR code is empty.' };
  if (!raw.startsWith(DEEP_LINK_SCHEME))
    return { ok: false, error: 'This is not a Tournament Organizer code.' };
  const parts = raw.slice(DEEP_LINK_SCHEME.length).split('/').filter(Boolean);
  if (parts.length !== 3) return { ok: false, error: 'This code is incomplete — scan a code generated by the app.' };
  const [projectId, kind, id] = parts;
  if (!(KINDS as string[]).includes(kind))
    return { ok: false, error: `Unknown code type "${kind}".` };
  if (!projectId || !id) return { ok: false, error: 'This code is missing an identifier.' };
  return { ok: true, link: { projectId, kind: kind as DeepLinkKind, id } };
}

export type ResolvedAction =
  | { kind: 'checkin'; participantId: string }
  | { kind: 'match'; matchId: string }
  | { kind: 'station'; resourceId: string }
  | { kind: 'error'; message: string };

/** Turns a link into a concrete action against the loaded project. */
export function resolveDeepLink(
  link: DeepLink,
  project: { id: string; participants: { id: string }[]; matches: { id: string }[]; resources: { id: string }[] },
): ResolvedAction {
  if (project.id !== link.projectId)
    return { kind: 'error', message: 'This code belongs to a different tournament project.' };
  if (link.kind === 'checkin') {
    return project.participants.some(p => p.id === link.id)
      ? { kind: 'checkin', participantId: link.id }
      : { kind: 'error', message: 'This participant is no longer in the project.' };
  }
  if (link.kind === 'match') {
    return project.matches.some(m => m.id === link.id)
      ? { kind: 'match', matchId: link.id }
      : { kind: 'error', message: 'This match no longer exists in the project.' };
  }
  return project.resources.some(r => r.id === link.id)
    ? { kind: 'station', resourceId: link.id }
    : { kind: 'error', message: 'This station is not part of the project any more.' };
}
