// Pro licensing — a signed entitlement, verified locally, offline forever.
//
// The rules this file exists to enforce:
//
//   * The only thing stored on this machine is a signed license envelope. There
//     is no "pro" flag anywhere: isProActive() is derived from a signature
//     check, so editing storage, the project file or a config file changes
//     nothing. A tampered envelope fails verification and the app is Free.
//   * Only the PUBLIC key is in the app. The private key lives in keys/ on the
//     machine that sells licenses (see scripts/generate-license-key.mjs) and is
//     never shipped, packaged or committed.
//   * An activation is only accepted for a signature we can verify, for this
//     product, not revoked, and not expired.
//   * What this cannot do, stated plainly: anyone who patches the app binary
//     can patch out a check. Signing makes forgery and casual editing useless;
//     it is not DRM, and it does not pretend to be.
//
// Honesty about the activation limit: with no server to call, the device count
// lives in local storage and can be deleted by a determined user. It stops
// casual sharing, not a determined cracker. revalidate() is the hook a
// published build can point at a license service later, and it is a no-op while
// offline, so the app never needs the network to run.

import { t } from '../i18n';
import { accessOf, FREE_FEATURE_IDS } from './feature-registry';

/** The edition an install is on. Derived, never stored. */
export type Tier = 'free' | 'pro';

/**
 * The raw Ed25519 public key, base64url. Generated by
 * `node scripts/generate-license-key.mjs`; that key pair is the one that can
 * issue licenses, so generate it once, before shipping.
 */
export const LICENSE_PUBLIC_KEY_B64 = 'rfTp3iwCXdZ9uX6P6OM2xtWsVt0FDkPwxdHBV6FkfvQ';

export const LICENSE_PRODUCT = 'tournament-organizer-pro';
export const LICENSE_CLAIMS_VERSION = 1;

/**
 * Test seam. The shipped app never calls this — no UI, no engine and no store
 * path touches it — so the key that ships is the only key a real install can
 * verify with. It exists so the test suite can drive the stateful functions
 * (activate / refresh / revalidate) with a throwaway key pair instead of the
 * production private key, which is not in this repository. Patching the app
 * binary would let an attacker do anything anyway; this is not what protects the
 * license, the signature check is.
 */
let publicKeyOverride: string | null = null;
export function setLicensePublicKey(b64: string | null): void { publicKeyOverride = b64; }
const activePublicKey = (): string => publicKeyOverride ?? LICENSE_PUBLIC_KEY_B64;
/** Where the signed envelope is cached. A file, never a boolean. */
const LS_LICENSE = 'to:license';
const LS_ACTIVATIONS = 'to:license-activations';
const LS_DEVICE = 'to:device-id';

export interface LicenseClaims {
  v: number;
  product: string;
  licenseId: string;
  customerEmail: string;
  customerName?: string;
  issuedAt: string;
  /** null = perpetual: this license never expires. */
  expiresAt: string | null;
  /** How many devices may activate. null = unlimited. */
  activationLimit: number | null;
  /** Which features the license unlocks. '*' means every Pro feature. */
  features: string[];
  /** A license the issuer disabled keeps its signature but stops working. */
  revoked?: boolean;
  issuedBy?: string;
}

export interface LicenseEnvelope {
  claims: LicenseClaims;
  /** base64url Ed25519 signature over canonicalize(claims). */
  signature: string;
}

export type LicenseFailure =
  | 'no-license' | 'malformed' | 'bad-signature' | 'wrong-product'
  | 'not-yet-valid' | 'expired' | 'revoked' | 'activation-limit' | 'no-public-key';

export type LicenseCheck =
  | { ok: true; claims: LicenseClaims }
  | { ok: false; reason: LicenseFailure };

const enc = new TextEncoder();

function b64ToBytes(s: string): Uint8Array {
  const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/'));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

const bytesToB64 = (b: ArrayBuffer | Uint8Array): string =>
  btoa(String.fromCharCode(...new Uint8Array(b as ArrayBuffer)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

/**
 * The exact bytes that are signed. Field order is fixed and absent fields are
 * normalised, so the issuer and the app always agree byte for byte.
 * scripts/sign-license.mjs builds the same string.
 */
export function canonicalize(c: LicenseClaims): string {
  return JSON.stringify({
    v: c.v,
    product: c.product,
    licenseId: c.licenseId,
    customerEmail: c.customerEmail,
    customerName: c.customerName ?? '',
    issuedAt: c.issuedAt,
    expiresAt: c.expiresAt,
    activationLimit: c.activationLimit,
    features: [...(c.features ?? [])].sort(),
    revoked: c.revoked === true,
    issuedBy: c.issuedBy ?? '',
  });
}

/** Parse a license as pasted: the JSON envelope, or the compact key form. */
export function parseLicense(text: string): LicenseEnvelope | null {
  const raw = (text ?? '').trim();
  if (!raw) return null;
  if (raw.startsWith('{')) {
    try {
      const parsed = JSON.parse(raw) as LicenseEnvelope;
      return parsed && typeof parsed === 'object' && parsed.claims && typeof parsed.signature === 'string'
        ? parsed : null;
    } catch { return null; }
  }
  // Compact form: TO-PRO.<claims>.<signature> — one line, fits an email.
  const parts = raw.split('.');
  if (parts.length !== 3 || parts[0] !== 'TO-PRO') return null;
  try {
    const claims = JSON.parse(new TextDecoder().decode(b64ToBytes(parts[1]))) as LicenseClaims;
    return { claims, signature: parts[2] };
  } catch { return null; }
}

/** The one-line form of a license, for email and for the support desk. */
export function formatLicenseKey(env: LicenseEnvelope): string {
  const b64 = (o: unknown) => bytesToB64(enc.encode(JSON.stringify(o)));
  return `TO-PRO.${b64(env.claims)}.${env.signature}`;
}

// ---- verification -----------------------------------------------------------

function subtle(): SubtleCrypto {
  const c = globalThis.crypto;
  if (!c?.subtle) throw new Error('no WebCrypto');
  return c.subtle;
}

/** Structure first (cheap, and it gives a precise reason), then the signature. */
function checkShape(env: LicenseEnvelope, now: Date): LicenseCheck {
  const c = env.claims;
  if (typeof c !== 'object' || c === null) return { ok: false, reason: 'malformed' };
  if (c.v !== LICENSE_CLAIMS_VERSION) return { ok: false, reason: 'malformed' };
  if (c.product !== LICENSE_PRODUCT) return { ok: false, reason: 'wrong-product' };
  if (typeof c.licenseId !== 'string' || !c.licenseId) return { ok: false, reason: 'malformed' };
  if (typeof c.customerEmail !== 'string' || !c.customerEmail.includes('@')) return { ok: false, reason: 'malformed' };
  if (!Array.isArray(c.features) || c.features.length === 0) return { ok: false, reason: 'malformed' };
  if (c.revoked === true) return { ok: false, reason: 'revoked' };
  const issued = Date.parse(c.issuedAt);
  if (!Number.isFinite(issued)) return { ok: false, reason: 'malformed' };
  // A day of clock skew, so a machine with a wrong date is not locked out.
  if (issued > now.getTime() + 24 * 3600_000) return { ok: false, reason: 'not-yet-valid' };
  // A perpetual license has expiresAt === null and never expires.
  if (c.expiresAt !== null) {
    const exp = Date.parse(c.expiresAt);
    if (!Number.isFinite(exp)) return { ok: false, reason: 'malformed' };
    if (exp <= now.getTime()) return { ok: false, reason: 'expired' };
  }
  return { ok: true, claims: c };
}

/**
 * Verify a license against a public key. Every unlock in the app goes through
 * here; nothing trusts a stored flag, a project file or a UI state.
 */
export async function verifyLicense(
  env: LicenseEnvelope,
  publicKeyB64: string = LICENSE_PUBLIC_KEY_B64,
  now: Date = new Date(),
): Promise<LicenseCheck> {
  const shape = checkShape(env, now);
  if (!shape.ok) return shape;
  if (!publicKeyB64) return { ok: false, reason: 'no-public-key' };
  try {
    const raw = b64ToBytes(publicKeyB64);
    if (raw.length !== 32) return { ok: false, reason: 'no-public-key' };
    const key = await subtle().importKey('raw', raw as BufferSource, { name: 'Ed25519' }, false, ['verify']);
    const ok = await subtle().verify(
      { name: 'Ed25519' },
      key,
      b64ToBytes(env.signature) as BufferSource,
      enc.encode(canonicalize(env.claims)) as BufferSource,
    );
    return ok ? shape : { ok: false, reason: 'bad-signature' };
  } catch {
    return { ok: false, reason: 'bad-signature' };
  }
}

// ---- storage (injectable: the Android shell and the tests supply their own) --

export interface KeyValueStore {
  getItem(k: string): string | null;
  setItem(k: string, v: string): void;
  removeItem(k: string): void;
}

const memory = new Map<string, string>();
const defaultStore = (): KeyValueStore => ({
  getItem: k => (typeof localStorage === 'undefined' ? memory.get(k) ?? null : localStorage.getItem(k)),
  setItem: (k, v) => { if (typeof localStorage === 'undefined') memory.set(k, v); else localStorage.setItem(k, v); },
  removeItem: k => { if (typeof localStorage === 'undefined') memory.delete(k); else localStorage.removeItem(k); },
});
let store: KeyValueStore = defaultStore();

/** Swap the backing store (Android bridge, tests). Pass nothing to reset. */
export function setLicenseStore(s?: KeyValueStore) { store = s ?? defaultStore(); }

export function loadLicense(): LicenseEnvelope | null {
  return parseLicense(store.getItem(LS_LICENSE) ?? '');
}
export function saveLicense(env: LicenseEnvelope): void {
  store.setItem(LS_LICENSE, JSON.stringify(env));
}
export function clearLicense(): void {
  store.removeItem(LS_LICENSE);
  store.removeItem(LS_ACTIVATIONS);
}

/** A stable id for this installation, used for device binding. */
export function deviceId(): string {
  let id = store.getItem(LS_DEVICE);
  if (!id) {
    const bytes = new Uint8Array(16);
    globalThis.crypto.getRandomValues(bytes);
    id = [...bytes].map(b => b.toString(16).padStart(2, '0')).join('');
    store.setItem(LS_DEVICE, id);
  }
  return id;
}

/** licenseId â†’ the devices that activated it on this machine. */
function activations(): Record<string, string[]> {
  try { return JSON.parse(store.getItem(LS_ACTIVATIONS) ?? '{}') as Record<string, string[]>; }
  catch { return {}; }
}

function recordActivation(licenseId: string, device: string) {
  const all = activations();
  const list = all[licenseId] ?? [];
  if (!list.includes(device)) list.push(device);
  all[licenseId] = list;
  store.setItem(LS_ACTIVATIONS, JSON.stringify(all));
}

/**
 * Enforce the activation limit. Returns a reason when the license itself is
 * valid but this machine is not allowed to use it.
 */
export function activationCheck(env: LicenseEnvelope, device: string = deviceId()): LicenseFailure | null {
  const limit = env.claims.activationLimit;
  if (limit === null || limit === undefined) return null;
  const used = activations()[env.claims.licenseId] ?? [];
  if (used.includes(device)) return null;
  if (used.length >= limit) return 'activation-limit';
  return null;
}

// ---- the verified state the whole app reads ---------------------------------

export interface LicenseState {
  status: 'free' | 'pro';
  claims: LicenseClaims | null;
  reason: LicenseFailure | null;
  checked: boolean;
}

let state: LicenseState = { status: 'free', claims: null, reason: 'no-license', checked: false };
const listeners = new Set<() => void>();
// publish() hands the new state back, so every function that ends in one can
// return it without a second read of the module variable.
const publish = (next: LicenseState): LicenseState => { state = next; listeners.forEach(l => l()); return state; };
const subscribe = (l: () => void) => { listeners.add(l); return () => { listeners.delete(l); }; };
export const licenseStore = { subscribe, get: () => state };

/** Verify whatever is stored and publish the result. Called at startup. */
export async function refreshLicense(now: Date = new Date()): Promise<LicenseState> {
  const env = loadLicense();
  if (!env) return publish({ status: 'free', claims: null, reason: 'no-license', checked: true });
  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) return publish({ status: 'free', claims: null, reason: verdict.reason, checked: true });
  const limit = activationCheck(env);
  if (limit) return publish({ status: 'free', claims: null, reason: limit, checked: true });
  return publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
}

export type ActivateResult =
  | { ok: true; claims: LicenseClaims }
  | { ok: false; reason: LicenseFailure };

/** Paste a key, import a file — the same path: parse, verify, bind this device. */
export async function activateLicense(text: string, now: Date = new Date()): Promise<ActivateResult> {
  const env = parseLicense(text);
  // Every refusal re-derives the state from what is actually stored, so a
  // rejected key can never leave a stale "Pro" sitting in memory.
  if (!env) { await refreshLicense(now); return { ok: false, reason: 'malformed' }; }
  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) { await refreshLicense(now); return { ok: false, reason: verdict.reason }; }
  const limit = activationCheck(env);
  if (limit) { await refreshLicense(now); return { ok: false, reason: limit }; }
  saveLicense(env);
  recordActivation(env.claims.licenseId, deviceId());
  publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
  return { ok: true, claims: verdict.claims };
}

export const importLicenseFile = activateLicense;

/** Give the license back: the app returns to Free and forgets this device. */
export function deactivateLicense(): void {
  clearLicense();
  publish({ status: 'free', claims: null, reason: 'no-license', checked: true });
}

/** The license as text, for a support request or a new machine. */
export function exportLicenseInfo(): string {
  const env = loadLicense();
  return env ? formatLicenseKey(env) : '';
}

/** Human-readable summary for the License screen. Never a raw dump. */
export function licenseSummary(): { status: string; detail: string } {
  if (!state.checked) return { status: t('lic.statusFree'), detail: '' };
  if (state.status === 'pro' && state.claims) {
    const c = state.claims;
    return {
      status: t('lic.statusPro'),
      detail: t('lic.detailPro', {
        who: c.customerName || c.customerEmail,
        issued: new Date(c.issuedAt).toLocaleDateString(),
        forever: c.expiresAt === null ? t('lic.forever') : new Date(c.expiresAt).toLocaleDateString(),
      }),
    };
  }
  return { status: t('lic.statusFree'), detail: state.reason ? t(`lic.reason.${state.reason}`) : '' };
}

export function isProActive(): boolean {
  return state.status === 'pro' && state.claims !== null;
}



/**
 * The single feature check. The list comes from the signed claims only — never
 * from a setting, a file the user can edit, or the UI.
 */
/**
 * The single feature check. The list comes from the signed claims only — never
 * from a setting, a file the user can edit, or the UI.
 *
 * With no license the answer is "the registry says this is free", read from
 * feature-registry.ts. That list used to be duplicated here, which was the one
 * place the registry and the license could have drifted apart.
 */
export function hasFeature(id: string): boolean {
  if (accessOf(id) === 'none') return false;   // unknown or not built: never granted
  if (!isProActive() || !state.claims) return FREE_FEATURE_IDS.includes(id);
  const f = state.claims.features;
  return f.includes('*') || f.includes(id);
}

/** The tier this install is on — derived, never stored. */
export function currentTier(): Tier {
  return isProActive() ? 'pro' : 'free';
}

/**
 * Optional server revalidation. With no endpoint configured this is a no-op,
 * so the app never needs the network; a published build can point it at a
 * license service later and revocation starts being noticed.
 */
let revalidator: ((env: LicenseEnvelope) => Promise<boolean>) | null = null;
export function setRevalidator(fn: ((env: LicenseEnvelope) => Promise<boolean>) | null) {
  revalidator = fn;
}

export async function revalidate(now: Date = new Date()): Promise<LicenseState> {
  const env = loadLicense();
  if (!env || !revalidator) return refreshLicense(now);
  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) return publish({ status: 'free', claims: null, reason: verdict.reason, checked: true });
  let alive = true;
  try { alive = await revalidator(env); } catch { alive = true; }   // offline keeps the license
  if (!alive) return publish({ status: 'free', claims: null, reason: 'revoked', checked: true });
  return publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
}


