// Pro licensing — a signed entitlement, verified locally, offline forever.
//
// The rules this file exists to enforce:
//
//   * The only thing stored on this machine is a signed license envelope. There
//     is no "pro" flag anywhere: isProActive() is derived from a signature
//     check, so editing storage, the project file or a config file changes
//     nothing. A tampered envelope fails verification and the app is Free.
//   * Only the PUBLIC key is in the app. The private key lives in keys/ on the
//     machine that sells licenses (see scripts/generate-license-key.mjs) and is
//     never shipped, packaged or committed.
//   * An activation is only accepted for a signature we can verify, for this
//     product, not revoked, and not expired.
//   * What this cannot do, stated plainly: anyone who patches the app binary
//     can patch out a check. Signing makes forgery and casual editing useless;
//     it is not DRM, and it does not pretend to be.
//
// Honesty about the activation limit: with no server to call, the device count
// lives in local storage and can be deleted by a determined user. It stops
// casual sharing, not a determined cracker. revalidate() is the hook a
// published build can point at a license service later, and it is a no-op while
// offline, so the app never needs the network to run.

import { t } from '../i18n';
import { accessOf, FREE_FEATURE_IDS } from './feature-registry';

/** The edition an install is on. Derived, never stored. */
export type Tier = 'free' | 'pro';

/**
 * The raw Ed25519 public key, base64url. Generated by
 * `node scripts/generate-license-key.mjs`; that key pair is the one that can
 * issue licenses, so generate it once, before shipping.
 */
export const LICENSE_PUBLIC_KEY_B64 = 'rfTp3iwCXdZ9uX6P6OM2xtWsVt0FDkPwxdHBV6FkfvQ';

export const LICENSE_PRODUCT = 'tournament-organizer-pro';
export const LICENSE_CLAIMS_VERSION = 1;

/**
 * Test seam. The shipped app never calls this — no UI, no engine and no store
 * path touches it — so the key that ships is the only key a real install can
 * verify with. It exists so the test suite can drive the stateful functions
 * (activate / refresh / revalidate) with a throwaway key pair instead of the
 * production private key, which is not in this repository. Patching the app
 * binary would let an attacker do anything anyway; this is not what protects the
 * license, the signature check is.
 */
let publicKeyOverride: string | null = null;
export function setLicensePublicKey(b64: string | null): void {
  // Compiled out of a production bundle: Vite replaces the check with a
  // literal, so the dead branch is dropped and this becomes a no-op function.
  // The point is that a real install has no reachable way to swap the key it
  // verifies against, even from the devtools console.
  if (import.meta.env?.PROD) return;
  publicKeyOverride = b64;
}
const activePublicKey = (): string => publicKeyOverride ?? LICENSE_PUBLIC_KEY_B64;
/** Where the signed envelope is cached. A file, never a boolean. */
const LS_LICENSE = 'to:license';
const LS_ACTIVATIONS = 'to:license-activations';
const LS_DEVICE = 'to:device-id';

export interface LicenseClaims {
  v: number;
  product: string;
  licenseId: string;
  customerEmail: string;
  customerName?: string;
  issuedAt: string;
  /** null = perpetual: this license never expires. */
  expiresAt: string | null;
  /** How many devices may activate. null = unlimited. */
  activationLimit: number | null;
  /**
   * How many activations the ISSUER had recorded when it signed this license —
   * normally 0 for a fresh sale.
   *
   * Be careful with this field. It cannot be the thing that enforces the limit:
   * it is covered by the signature, so the app cannot increment it without
   * invalidating the license it is reading. The app therefore treats it as the
   * issuer's baseline and keeps the running count in its own device ledger
   * (see activationUsageOf). Treat this as "what the seller knew when they sold",
   * never as "what is true right now" — that is what makes it safe to sign.
   */
  activationUsage: number;
  /** Which features the license unlocks. '*' means every Pro feature. */
  features: string[];
  /** A license the issuer disabled keeps its signature but stops working. */
  revoked?: boolean;
  issuedBy?: string;
}

export interface LicenseEnvelope {
  claims: LicenseClaims;
  /** base64url Ed25519 signature over canonicalize(claims). */
  signature: string;
}

export type LicenseFailure =
  | 'no-license' | 'malformed' | 'bad-signature' | 'wrong-product'
  | 'not-yet-valid' | 'expired' | 'revoked' | 'activation-limit' | 'no-public-key';

export type LicenseCheck =
  | { ok: true; claims: LicenseClaims }
  | { ok: false; reason: LicenseFailure };

const enc = new TextEncoder();

function b64ToBytes(s: string): Uint8Array {
  const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/'));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

const bytesToB64 = (b: ArrayBuffer | Uint8Array): string =>
  btoa(String.fromCharCode(...new Uint8Array(b as ArrayBuffer)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

/**
 * The exact bytes that are signed. Field order is fixed and absent fields are
 * normalised, so the issuer and the app always agree byte for byte.
 * scripts/sign-license.mjs builds the same string.
 */
export function canonicalize(c: LicenseClaims): string {
  return JSON.stringify({
    v: c.v,
    product: c.product,
    licenseId: c.licenseId,
    customerEmail: c.customerEmail,
    customerName: c.customerName ?? '',
    issuedAt: c.issuedAt,
    expiresAt: c.expiresAt,
    activationLimit: c.activationLimit,
    activationUsage: c.activationUsage ?? 0,
    features: [...(c.features ?? [])].sort(),
    revoked: c.revoked === true,
    issuedBy: c.issuedBy ?? '',
  });
}

/** Parse a license as pasted: the JSON envelope, or the compact key form. */
export function parseLicense(text: string): LicenseEnvelope | null {
  const raw = (text ?? '').trim();
  if (!raw) return null;
  if (raw.startsWith('{')) {
    try {
      const parsed = JSON.parse(raw) as LicenseEnvelope;
      return parsed && typeof parsed === 'object' && parsed.claims && typeof parsed.signature === 'string'
        ? parsed : null;
    } catch { return null; }
  }
  // Compact form: TO-PRO.<claims>.<signature> — one line, fits an email.
  const parts = raw.split('.');
  if (parts.length !== 3 || parts[0] !== 'TO-PRO') return null;
  try {
    const claims = JSON.parse(new TextDecoder().decode(b64ToBytes(parts[1]))) as LicenseClaims;
    return { claims, signature: parts[2] };
  } catch { return null; }
}

/** The one-line form of a license, for email and for the support desk. */
export function formatLicenseKey(env: LicenseEnvelope): string {
  const b64 = (o: unknown) => bytesToB64(enc.encode(JSON.stringify(o)));
  return `TO-PRO.${b64(env.claims)}.${env.signature}`;
}

// ---- verification -----------------------------------------------------------

function subtle(): SubtleCrypto {
  const c = globalThis.crypto;
  if (!c?.subtle) throw new Error('no WebCrypto');
  return c.subtle;
}

/** Bounds for a claim. A license is machine-written, never prose. */
const MAX_ID = 128;
const MAX_EMAIL = 254;
const MAX_NAME = 200;
const MAX_FEATURES = 64;

const malformed = (): LicenseCheck => ({ ok: false, reason: 'malformed' });
const str = (v: unknown, max: number): boolean => typeof v === 'string' && v.length > 0 && v.length <= max;
/** A count that must be a real, non-negative, finite integer. */
const count = (v: unknown): boolean => Number.isInteger(v) && (v as number) >= 0;

/**
 * Structure and range, before the signature is even looked at.
 *
 * This is deliberately strict. Every field is checked for type, length and range,
 * because a claim that slips through here as a string where a number belongs can
 * turn an arithmetic comparison into `NaN >= NaN` — which is false, which reads
 * as "limit not reached", which is the wrong way to fail. A malformed license
 * must refuse, never shrug.
 */
function checkShape(env: LicenseEnvelope, now: Date): LicenseCheck {
  if (typeof env !== 'object' || env === null) return malformed();
  if (typeof env.signature !== 'string' || env.signature.length < 16 || env.signature.length > 256) return malformed();

  const c = env.claims;
  if (typeof c !== 'object' || c === null) return malformed();
  if (c.v !== LICENSE_CLAIMS_VERSION) return malformed();
  if (c.product !== LICENSE_PRODUCT) return { ok: false, reason: 'wrong-product' };

  if (!str(c.licenseId, MAX_ID)) return malformed();
  if (!str(c.customerEmail, MAX_EMAIL) || !c.customerEmail.includes('@')) return malformed();
  if (c.customerName !== undefined && typeof c.customerName !== 'string') return malformed();
  if (typeof c.customerName === 'string' && c.customerName.length > MAX_NAME) return malformed();

  // An explicit revocation is honoured even when the signature is perfectly
  // valid — that is the whole point of keeping the flag inside the signed bytes.
  if (c.revoked !== undefined && typeof c.revoked !== 'boolean') return malformed();
  if (c.revoked === true) return { ok: false, reason: 'revoked' };
  if (c.issuedBy !== undefined && typeof c.issuedBy !== 'string') return malformed();

  const issued = Date.parse(c.issuedAt);
  if (typeof c.issuedAt !== 'string' || !Number.isFinite(issued)) return malformed();
  // A day of clock skew, so a machine with a wrong date is not locked out.
  if (issued > now.getTime() + 24 * 3600_000) return { ok: false, reason: 'not-yet-valid' };

  // A perpetual license has expiresAt === null and never expires.
  if (c.expiresAt !== null) {
    const exp = Date.parse(c.expiresAt);
    if (typeof c.expiresAt !== 'string' || !Number.isFinite(exp)) return malformed();
    if (exp <= now.getTime()) return { ok: false, reason: 'expired' };
  }

  // Limits: null (unlimited) or a real count. A negative, fractional, NaN or
  // missing limit is a forged license, not a generous one.
  if (c.activationLimit !== null && !count(c.activationLimit)) return malformed();
  if (!count(c.activationUsage)) return malformed();

  if (!Array.isArray(c.features) || c.features.length === 0 || c.features.length > MAX_FEATURES) return malformed();
  if (!c.features.every(f => str(f, MAX_ID))) return malformed();

  return { ok: true, claims: c };
}

/**
 * Verify a license against a public key. Every unlock in the app goes through
 * here; nothing trusts a stored flag, a project file or a UI state.
 */
export async function verifyLicense(
  env: LicenseEnvelope,
  publicKeyB64: string = LICENSE_PUBLIC_KEY_B64,
  now: Date = new Date(),
): Promise<LicenseCheck> {
  const shape = checkShape(env, now);
  if (!shape.ok) return shape;
  if (!publicKeyB64) return { ok: false, reason: 'no-public-key' };
  try {
    const raw = b64ToBytes(publicKeyB64);
    if (raw.length !== 32) return { ok: false, reason: 'no-public-key' };
    const key = await subtle().importKey('raw', raw as BufferSource, { name: 'Ed25519' }, false, ['verify']);
    const ok = await subtle().verify(
      { name: 'Ed25519' },
      key,
      b64ToBytes(env.signature) as BufferSource,
      enc.encode(canonicalize(env.claims)) as BufferSource,
    );
    return ok ? shape : { ok: false, reason: 'bad-signature' };
  } catch {
    return { ok: false, reason: 'bad-signature' };
  }
}

// ---- storage (injectable: the Android shell and the tests supply their own) --

export interface KeyValueStore {
  getItem(k: string): string | null;
  setItem(k: string, v: string): void;
  removeItem(k: string): void;
}

const memory = new Map<string, string>();
const defaultStore = (): KeyValueStore => ({
  getItem: k => (typeof localStorage === 'undefined' ? memory.get(k) ?? null : localStorage.getItem(k)),
  setItem: (k, v) => { if (typeof localStorage === 'undefined') memory.set(k, v); else localStorage.setItem(k, v); },
  removeItem: k => { if (typeof localStorage === 'undefined') memory.delete(k); else localStorage.removeItem(k); },
});
let store: KeyValueStore = defaultStore();

/** Swap the backing store (Android bridge, tests). Pass nothing to reset. */
export function setLicenseStore(s?: KeyValueStore) { store = s ?? defaultStore(); }

export function loadLicense(): LicenseEnvelope | null {
  return parseLicense(store.getItem(LS_LICENSE) ?? '');
}
export function saveLicense(env: LicenseEnvelope): void {
  store.setItem(LS_LICENSE, JSON.stringify(env));
}

/**
 * Wipe the cached entitlement AND the local device ledger. Internal: both
 * public removal paths go through deactivateLicense() or removeLicense(), which
 * differ on purpose.
 */
export function clearLicense(): void {
  store.removeItem(LS_LICENSE);
  store.removeItem(LS_ACTIVATIONS);
}

/** A stable id for this installation, used for device binding. */
export function deviceId(): string {
  let id = store.getItem(LS_DEVICE);
  if (!id) {
    const bytes = new Uint8Array(16);
    globalThis.crypto.getRandomValues(bytes);
    id = [...bytes].map(b => b.toString(16).padStart(2, '0')).join('');
    store.setItem(LS_DEVICE, id);
  }
  return id;
}

/** licenseId → the devices that activated it on this machine. */
function activations(): Record<string, string[]> {
  try { return JSON.parse(store.getItem(LS_ACTIVATIONS) ?? '{}') as Record<string, string[]>; }
  catch { return {}; }
}

/**
 * The activation count the app actually enforces: the signed baseline plus any
 * device recorded here that the issuer did not know about yet. Reported on the
 * License screen so a customer and support see the same number, and so a reset
 * is visible rather than silent.
 *
 * This is the honest limit of an offline design: it stops casual sharing, and a
 * determined user can delete this ledger. Making it tamper-proof needs a server,
 * which is exactly what `revalidate()` is for later.
 */
export function activationUsageOf(env: LicenseEnvelope): number {
  const issued = Math.max(0, env.claims.activationUsage ?? 0);
  const local = (activations()[env.claims.licenseId] ?? []).length;
  return Math.max(issued, local);
}

function recordActivation(licenseId: string, device: string) {
  const all = activations();
  const list = all[licenseId] ?? [];
  if (!list.includes(device)) list.push(device);
  all[licenseId] = list;
  store.setItem(LS_ACTIVATIONS, JSON.stringify(all));
}

/**
 * Enforce the activation limit. Returns a reason when the license itself is
 * valid but this machine is not allowed to use it.
 *
 * The count is the signed baseline reconciled with the local ledger, so a
 * license sold with one activation already used is refused on a second machine
 * even if that machine's ledger is empty.
 */
export function activationCheck(env: LicenseEnvelope, device: string = deviceId()): LicenseFailure | null {
  const limit = env.claims.activationLimit;
  if (limit === null || limit === undefined) return null;
  // A device already on this license is coming back, not taking a new seat.
  if ((activations()[env.claims.licenseId] ?? []).includes(device)) return null;
  return activationUsageOf(env) >= limit ? 'activation-limit' : null;
}

// ---- the verified state the whole app reads ---------------------------------

export interface LicenseState {
  status: 'free' | 'pro';
  claims: LicenseClaims | null;
  reason: LicenseFailure | null;
  checked: boolean;
}

let state: LicenseState = { status: 'free', claims: null, reason: 'no-license', checked: false };
const listeners = new Set<() => void>();
// publish() hands the new state back, so every function that ends in one can
// return it without a second read of the module variable.
const publish = (next: LicenseState): LicenseState => { state = next; listeners.forEach(l => l()); return state; };
const subscribe = (l: () => void) => { listeners.add(l); return () => { listeners.delete(l); }; };
export const licenseStore = { subscribe, get: () => state };

/** Verify whatever is stored and publish the result. Called at startup. */
export async function refreshLicense(now: Date = new Date()): Promise<LicenseState> {
  const env = loadLicense();
  if (!env) return publish({ status: 'free', claims: null, reason: 'no-license', checked: true });
  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) return publish({ status: 'free', claims: null, reason: verdict.reason, checked: true });
  const limit = activationCheck(env);
  if (limit) return publish({ status: 'free', claims: null, reason: limit, checked: true });
  return publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
}

export type ActivateResult =
  | { ok: true; claims: LicenseClaims }
  | { ok: false; reason: LicenseFailure };

/** Paste a key, import a file — the same path: parse, verify, bind this device. */
export async function activateLicense(text: string, now: Date = new Date()): Promise<ActivateResult> {
  const env = parseLicense(text);
  // Every refusal re-derives the state from what is actually stored, so a
  // rejected key can never leave a stale "Pro" sitting in memory.
  if (!env) { await refreshLicense(now); return { ok: false, reason: 'malformed' }; }
  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) { await refreshLicense(now); return { ok: false, reason: verdict.reason }; }
  const limit = activationCheck(env);
  if (limit) { await refreshLicense(now); return { ok: false, reason: limit }; }
  saveLicense(env);
  recordActivation(env.claims.licenseId, deviceId());
  publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
  return { ok: true, claims: verdict.claims };
}

export const importLicenseFile = activateLicense;

/**
 * Give the license back. The app returns to Free AND this device's seat is
 * released, so the customer can activate it somewhere else — the operation the
 * License screen offers when someone is moving machines.
 */
export function deactivateLicense(): void {
  clearLicense();
  publish({ status: 'free', claims: null, reason: 'no-license', checked: true });
}

/**
 * Remove the license from this machine WITHOUT giving the seat back.
 *
 * The distinction matters. Deactivate is a promise to the customer: the license
 * moves. Remove is what you want on a machine you are handing to someone else or
 * wiping — the entitlement is gone from this computer, and the seat stays
 * consumed so the license cannot be quietly duplicated onto it.
 *
 * Re-importing the same license afterwards still works, because this device is
 * still on the license's ledger; it simply stops being Pro until it does.
 */
export function removeLicense(): void {
  store.removeItem(LS_LICENSE);
  publish({ status: 'free', claims: null, reason: 'no-license', checked: true });
}

/** The license as text, for a support request or a new machine. */
export function exportLicenseInfo(): string {
  const env = loadLicense();
  return env ? formatLicenseKey(env) : '';
}

/** Human-readable summary for the License screen. Never a raw dump. */
export function licenseSummary(): { status: string; detail: string } {
  if (!state.checked) return { status: t('lic.statusFree'), detail: '' };
  if (state.status === 'pro' && state.claims) {
    const c = state.claims;
    return {
      status: t('lic.statusPro'),
      detail: t('lic.detailPro', {
        who: c.customerName || c.customerEmail,
        issued: new Date(c.issuedAt).toLocaleDateString(),
        forever: c.expiresAt === null ? t('lic.forever') : new Date(c.expiresAt).toLocaleDateString(),
      }),
    };
  }
  return { status: t('lic.statusFree'), detail: state.reason ? t(`lic.reason.${state.reason}`) : '' };
}

export function isProActive(): boolean {
  return state.status === 'pro' && state.claims !== null;
}



/**
 * The single feature check. The list comes from the signed claims only — never
 * from a setting, a file the user can edit, or the UI.
 */
/**
 * The single feature check. The list comes from the signed claims only — never
 * from a setting, a file the user can edit, or the UI.
 *
 * With no license the answer is "the registry says this is free", read from
 * feature-registry.ts. That list used to be duplicated here, which was the one
 * place the registry and the license could have drifted apart.
 */
export function hasFeature(id: string): boolean {
  if (accessOf(id) === 'none') return false;   // unknown or not built: never granted
  if (!isProActive() || !state.claims) return FREE_FEATURE_IDS.includes(id);
  const f = state.claims.features;
  return f.includes('*') || f.includes(id);
}

/** The tier this install is on — derived, never stored. */
export function currentTier(): Tier {
  return isProActive() ? 'pro' : 'free';
}

/**
 * Optional server revalidation. With no endpoint configured this is a no-op,
 * so the app never needs the network; a published build can point it at a
 * license service later and revocation starts being noticed.
 */
let revalidator: ((env: LicenseEnvelope) => Promise<boolean>) | null = null;
export function setRevalidator(fn: ((env: LicenseEnvelope) => Promise<boolean>) | null) {
  revalidator = fn;
}

/**
 * How often to ask, if there is anything to ask. Six hours is a compromise:
 * long enough that a laptop on a train never stalls on a network, short enough
 * that a revoked license stops working within a working day.
 *
 * Without a revalidator configured this is never consulted — the app does not
 * keep a timer running to discover there is no server.
 */
export const REVALIDATE_INTERVAL_MS = 6 * 60 * 60 * 1000;

const LS_LAST_REVALIDATE = 'to:license-revalidated-at';

/**
 * The revalidation policy, in one place so it cannot drift:
 *   * verify the signature first, every time — offline or not;
 *   * ask the server only when one is configured and the interval has passed;
 *   * a network failure NEVER revokes. Offline-first is the product's promise,
 *     and a train tunnel must not take someone's license away.
 */
export async function revalidate(now: Date = new Date()): Promise<LicenseState> {
  const env = loadLicense();
  if (!env || !revalidator) return refreshLicense(now);

  const verdict = await verifyLicense(env, activePublicKey(), now);
  if (!verdict.ok) return publish({ status: 'free', claims: null, reason: verdict.reason, checked: true });

  const last = Number(store.getItem(LS_LAST_REVALIDATE) ?? 0);
  if (Number.isFinite(last) && last > 0 && now.getTime() - last < REVALIDATE_INTERVAL_MS) {
    // Too soon — keep the verified result rather than calling the server again.
    return publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
  }

  let alive = true;
  try {
    alive = await revalidator(env);
  } catch {
    alive = true;                       // unreachable server ≠ revoked license
  }
  if (!alive) return publish({ status: 'free', claims: null, reason: 'revoked', checked: true });

  store.setItem(LS_LAST_REVALIDATE, String(now.getTime()));
  return publish({ status: 'pro', claims: verdict.claims, reason: null, checked: true });
}


