// What each tournament mode means, which settings it actually needs, and what
// the app will generate for a given field size.
//
// This is the single source of truth behind the setup screens: the mode picker,
// the explanations, the presets, the visible settings and the preview all read
// from here, so a format can never be described one way and generated another.
// Pure and deterministic — no DOM, no randomness, no tournament state.
import { t, type Dict } from '../i18n';
import { CompetitionFormat, DrawResolution, GENERATED_CUSTOM_STAGES, Match, Participant, RuleSet, ValidationIssueLike } from './types';
import { genSingleElim } from './elim';
import { genDoubleElim } from './double';
import { genGroupsKnockout, genLeague, genRoundRobin } from './generate';
import { swissPairings } from './swiss';

export type SettingGroup =
  | 'scoring'      // points per result
  | 'draws'        // whether a level match may end level, and how it is settled
  | 'tiebreak'     // how equal points are separated
  | 'seeding'      // who plays whom in the first round
  | 'groups'       // group count and who advances
  | 'rounds'       // how many Swiss rounds
  | 'meeting'      // home & away
  | 'byes'         // free pass points for an odd field
  | 'structure'    // which stage a custom event is built from
  | 'reporting';   // points kept only for reports and exports

export interface ModeInfo {
  format: CompetitionFormat;
  /** Where the mode lives in the picker — by intent, not by feature name. */
  group: 'quick' | 'ranking' | 'groups' | 'other';
  /** One-line meaning, plain language, no jargon. */
  meaning: keyof Dict;
  /** A concrete, checkable example: "8 players → …". */
  example: keyof Dict;
  goodFor: keyof Dict;
  notIncluded: keyof Dict;
  /** Setting groups this mode genuinely needs; anything else is not shown. */
  settings: readonly SettingGroup[];
  /** Points are part of the result here (a table is produced). */
  points: boolean;
  /** The event ends in a knockout bracket. */
  bracket: boolean;
  /** The whole fixture list is generated in one go. */
  autoGenerated: boolean;
}

/**
 * The catalogue. Order inside each group is the order the picker shows.
 *
 * `points` and `bracket` are the same facts the engine uses to decide whether a
 * ranking table or a bracket makes sense — see hasPointTable()/hasBracket().
 */
export const MODES: readonly ModeInfo[] = [
  {
    format: 'single-elimination', group: 'quick',
    meaning: 'format.meaning.single-elimination',
    example: 'format.example.single-elimination',
    goodFor: 'format.for.single-elimination',
    notIncluded: 'format.not.single-elimination',
    // A bracket decides on the match result. Points are kept only as reporting
    // metadata, and a level match needs an explicit rule to be settled.
    settings: ['seeding', 'draws', 'reporting'],
    points: false, bracket: true, autoGenerated: true,
  },
  {
    format: 'double-elimination', group: 'quick',
    meaning: 'format.meaning.double-elimination',
    example: 'format.example.double-elimination',
    goodFor: 'format.for.double-elimination',
    notIncluded: 'format.not.double-elimination',
    settings: ['seeding', 'draws', 'reporting'],
    points: false, bracket: true, autoGenerated: true,
  },
  {
    format: 'groups-knockout', group: 'groups',
    meaning: 'format.meaning.groups-knockout',
    example: 'format.example.groups-knockout',
    goodFor: 'format.for.groups-knockout',
    notIncluded: 'format.not.groups-knockout',
    settings: ['scoring', 'draws', 'tiebreak', 'seeding', 'groups'],
    points: true, bracket: true, autoGenerated: true,
  },
  {
    format: 'round-robin', group: 'ranking',
    meaning: 'format.meaning.round-robin',
    example: 'format.example.round-robin',
    goodFor: 'format.for.round-robin',
    notIncluded: 'format.not.round-robin',
    settings: ['scoring', 'draws', 'tiebreak', 'seeding', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'swiss', group: 'ranking',
    meaning: 'format.meaning.swiss',
    example: 'format.example.swiss',
    goodFor: 'format.for.swiss',
    notIncluded: 'format.not.swiss',
    settings: ['scoring', 'draws', 'tiebreak', 'rounds', 'byes'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'league', group: 'ranking',
    meaning: 'format.meaning.league',
    example: 'format.example.league',
    goodFor: 'format.for.league',
    notIncluded: 'format.not.league',
    settings: ['scoring', 'draws', 'tiebreak', 'seeding', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'team-match', group: 'other',
    meaning: 'format.meaning.team-match',
    example: 'format.example.team-match',
    goodFor: 'format.for.team-match',
    notIncluded: 'format.not.team-match',
    settings: ['scoring', 'draws', 'tiebreak', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'individual-match', group: 'other',
    meaning: 'format.meaning.individual-match',
    example: 'format.example.individual-match',
    goodFor: 'format.for.individual-match',
    notIncluded: 'format.not.individual-match',
    settings: ['scoring', 'draws', 'tiebreak', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'custom', group: 'other',
    meaning: 'format.meaning.custom',
    example: 'format.example.custom',
    goodFor: 'format.for.custom',
    notIncluded: 'format.not.custom',
    // Custom is the mode that exposes every rule combination on purpose, so a
    // setting is never hidden here — only labelled for what it affects. It also
    // has to state which stage it is, instead of the app assuming one.
    settings: ['scoring', 'draws', 'tiebreak', 'seeding', 'groups', 'rounds', 'meeting', 'byes', 'structure'],
    points: true, bracket: false, autoGenerated: true,
  },
];

const BY_FORMAT = new Map<CompetitionFormat, ModeInfo>(MODES.map((m) => [m.format, m]));

/** The catalogue entry for a format; anything unknown is treated as Custom. */
export function modeOf(format: string): ModeInfo {
  return BY_FORMAT.get(format as CompetitionFormat) ?? modeOf('custom');
}

/** Only these setting groups are shown for a format — the rest stay hidden. */
export function settingGroupsFor(format: string): readonly SettingGroup[] {
  return modeOf(format).settings;
}

// ---- what the app will generate --------------------------------------------

export interface PreviewRow { key: keyof Dict; value: string }

export interface StructurePreview {
  format: CompetitionFormat;
  /** Which kind of output the organizer gets. */
  kind: 'bracket' | 'table' | 'groups' | 'rounds' | 'fixtures';
  titleKey: keyof Dict;
  rows: PreviewRow[];
  notes: (keyof Dict)[];
  /** Matches that exist as soon as the organizer presses generate. */
  matches: number | null;
  /** Matches that only appear later — the next Swiss round, the knockout. */
  later: number;
  /** Free passes the plan contains. A bye is a slot, not a match to play. */
  byes: number;
  /** The field size the numbers were computed for. */
  count: number;
  /** True when the numbers come from a sample, not a real participant count. */
  assumed: boolean;
}

/** Field size used for the preview when the organizer has not said. */
export const PREVIEW_SAMPLE = 8;

function pow2(n: number): number {
  let r = 1;
  while (r < n) r *= 2;
  return r;
}
const choose2 = (n: number) => (n * (n - 1)) / 2;

/** Rounds a round robin needs: one per opponent, plus one when someone sits out. */
function rrRounds(n: number): number {
  return n % 2 === 1 ? n : n - 1;
}

function syntheticField(count: number): Participant[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `preview_${i}`,
    name: `P${i + 1}`,
    kind: 'player' as const,
    active: true,
    seed: i + 1,
    tags: [],
  }));
}

/**
 * What the real generator would create for a field of this size — counted, not
 * estimated, by running it on a synthetic field. Seeding is forced to the input
 * order so the count is deterministic; the order of the pairings never changes
 * how many matches there are.
 *
 * Byes are counted apart: the app stores a free pass as a match row, but nobody
 * plays it, and a preview that counted it would overstate the work.
 */
function planned(format: string, count: number, rules: RuleSet): { played: number; byes: number } {
  const ps = syntheticField(count);
  const r: RuleSet = { ...rules, seeding: 'seeded' };
  const all: Match[] =
    format === 'single-elimination' ? genSingleElim(ps, r).matches
      : format === 'double-elimination' ? genDoubleElim(ps, r).matches
        : format === 'league' ? genLeague(ps, r)
          : format === 'groups-knockout' ? genGroupsKnockout(ps, r).matches
            : format === 'swiss' ? swissPairings(ps, [], new Map(ps.map(p => [p.id, 0])), 1)
              : genRoundRobin(ps, r);
  // A free pass is a row with one participant and no opponent. A row with two
  // empty slots is not a bye at all — it is a later round waiting for a result,
  // and it still belongs to the total the organizer will play.
  const byes = all.filter(m => (m.homeId === null) !== (m.awayId === null)).length;
  return { played: all.length - byes, byes };
}

/**
 * Describes the output for a format at a given field size, so the setup screens
 * can show it live and tests can hold it against the generators.
 */
export function previewStructure(
  format: string,
  participantCount: number | null | undefined,
  rules: RuleSet,
): StructurePreview {
  const mode = modeOf(format);
  const real = typeof participantCount === 'number' && participantCount >= 2;
  const count = real ? Math.floor(participantCount) : PREVIEW_SAMPLE;
  const rows: PreviewRow[] = [];
  const notes: (keyof Dict)[] = [];
  let kind: StructurePreview['kind'] = 'bracket';
  let matches: number | null = null;
  let later = 0;
  let byes = 0;
  const push = (key: keyof Dict, value: string | number) => rows.push({ key, value: String(value) });
  const byeRows = () => { if (byes > 0) push('preview.byes', byes); };

  switch (format) {
    case 'single-elimination': {
      const size = pow2(count);
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.rounds', Math.log2(size));
      push('preview.matches', matches);
      byeRows();
      if (size > count) notes.push('preview.noteByes');
      push('preview.ends', t('preview.endsFinal'));
      break;
    }
    case 'double-elimination': {
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.winnersLosers', t('preview.wlCount', { n: Math.max(0, matches - 1) }));
      push('preview.grandFinal', 1);
      push('preview.matches', matches);
      byeRows();
      notes.push('preview.noteReset');
      break;
    }
    case 'round-robin':
    case 'team-match':
    case 'individual-match':
    case 'custom': {
      kind = format === 'custom' ? 'fixtures' : 'table';
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.rounds', rrRounds(count));
      push('preview.matches', matches);
      byeRows();
      if (byes > 0) notes.push('preview.noteRRBye');
      push('preview.meetings', rules.homeAway ? t('preview.twice') : t('preview.once'));
      push('preview.ends', t('preview.endsTable'));
      if (format === 'custom') notes.push('preview.noteCustom');
      break;
    }
    case 'league': {
      kind = 'table';
      ({ played: matches, byes } = planned(format, count, rules));
      const double = rules.homeAway ?? true;
      push('preview.matchdays', rrRounds(count) * (double ? 2 : 1));
      push('preview.matches', matches);
      byeRows();
      if (byes > 0) notes.push('preview.noteRRBye');
      push('preview.meetings', double ? t('preview.twice') : t('preview.once'));
      push('preview.ends', t('preview.endsTable'));
      break;
    }
    case 'swiss': {
      // Only the first round exists after generating; the rest are paired from
      // the standings, round by round, as results come in.
      kind = 'rounds';
      const plannedRounds = Math.max(1, rules.swissRounds ?? 5);
      const first = planned(format, count, rules);
      matches = first.played;
      byes = first.byes;
      const perRound = first.played + first.byes;
      later = (plannedRounds - 1) * perRound;
      push('preview.roundsPlanned', plannedRounds);
      push('preview.matchesPerRound', perRound);
      push('preview.matchesTotal', perRound * plannedRounds);
      notes.push('preview.noteSwiss');
      if (byes > 0) notes.push('preview.noteSwissBye');
      break;
    }
    case 'groups-knockout': {
      // The group stage is generated now; the bracket is built from the
      // qualifiers once the groups are finished.
      kind = 'groups';
      const plan = groupPlan(rules, count);
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.groups', plan.groups);
      push('preview.groupSizes', plan.sizes.join(' / '));
      push('preview.groupMatches', matches);
      byeRows();
      push('preview.qualifiers', plan.qualifiers);
      later = Math.max(0, plan.qualifiers - 1);
      push('preview.koMatches', later);
      if (plan.knockoutByes > 0) push('preview.koByes', plan.knockoutByes);
      if (plan.uneven) notes.push('preview.noteUnevenGroups');
      notes.push('preview.noteGroupsKo');
      break;
    }
    default:
      kind = 'bracket';
  }

  return {
    format: mode.format,
    kind,
    titleKey: mode.points && !mode.bracket ? 'preview.titleTable' : 'preview.titleStructure',
    rows,
    notes,
    matches,
    later,
    byes,
    count,
    assumed: !real,
  };
}

// ---- the plan: stages, flow and what stays manual --------------------------

export interface StagePlan {
  key: keyof Dict;
  produces: keyof Dict;
  flow: keyof Dict;
  /** False for a stage the organizer has to run, or the engine, not the app. */
  generatedNow: boolean;
  /** What this stage costs in matches at the given field size, when known. */
  matches: number | null;
}

/**
 * The stages this format runs, with the ones the app builds now marked against
 * the ones the organizer runs later. Swiss is the clearest case: round 1 is
 * generated, every later round is paired from the standings after results come
 * in, and a group stage is generated while the knockout waits for qualifiers.
 */
export function stagePlan(
  format: string,
  rules: RuleSet,
  participantCount?: number | null,
): StagePlan[] {
  const spec = specFor(format);
  const p = previewStructure(format, participantCount, rules);
  const real = typeof participantCount === 'number' && participantCount >= 2;
  const plannedRounds = Math.max(1, rules.swissRounds ?? 5);
  return spec.stages.map((s, i) => {
    let matches: number | null = null;
    let generatedNow = true;
    if (format === 'swiss') {
      generatedNow = i === 0;
      matches = i === 0 ? p.matches : (plannedRounds > 1 ? Math.floor(((p.matches ?? 0) + p.byes)) : 0);
    } else if (format === 'groups-knockout') {
      generatedNow = i === 0;
      matches = i === 0 ? p.matches : p.later;
    } else if (format === 'double-elimination') {
      // The grand final is one match, and it exists from the start.
      matches = i === 2 ? 1 : null;
    } else {
      matches = i === 0 ? p.matches : null;
    }
    if (!real && format === 'swiss' && i > 0) matches = null;
    return { key: s.key, produces: s.produces, flow: s.flow, generatedNow, matches };
  });
}

/** What the organizer still has to do by hand in this format. */
export function manualSteps(format: string): (keyof Dict)[] {
  switch (format) {
    case 'swiss': return ['mode.manual.nextRound', 'mode.manual.byeEntry'];
    case 'groups-knockout': return ['mode.manual.qualifiers', 'mode.manual.knockout'];
    case 'double-elimination': return ['mode.manual.deadMatch'];
    case 'custom': return ['mode.manual.customStages'];
    case 'single-elimination': return ['mode.manual.deadMatch'];
    default: return ['mode.manual.venues'];
  }
}

/**
 * True when the plan cannot be counted yet: fewer than two participants, or a
 * field size the mode cannot take. The screens warn about it before creation
 * rather than saving a tournament nobody can generate.
 */
export function previewWarning(
  format: string,
  rules: RuleSet,
  participantCount?: number | null,
): keyof Dict | null {
  const n = typeof participantCount === 'number' ? Math.floor(participantCount) : null;
  if (n === null) return null;                     // a sample is shown and labelled
  if (n < 2) return 'mode.warn.tooFew';
  if (format === 'groups-knockout') {
    const groups = Math.max(2, Math.floor(rules.groupCount ?? 2));
    if (n < groups * 2) return 'mode.warn.groupSize';
  }
  if (format === 'swiss' && n < 3) return 'mode.warn.tooFew';
  if (format === 'league' && n < 3) return 'mode.warn.leagueTooFew';
  return null;
}

// ---- does this combination of rules make sense? ----------------------------

/**
 * Rule combinations that are legal but almost certainly not what the organizer
 * meant, plus the combinations the mode rules forbid outright.
 *
 * The same shape the engine's validation uses, so the setup screens and
 * `validateTournament` share it. Pure: it only reads rules and field size.
 */
export function validateModeSetup(
  format: string,
  rules: RuleSet,
  participantCount?: number | null,
): ValidationIssueLike[] {
  const issues: ValidationIssueLike[] = [];
  const n = typeof participantCount === 'number' && participantCount >= 2
    ? Math.floor(participantCount)
    : null;
  const spec = specFor(format);

  // --- points, in every mode -------------------------------------------------
  if (showsField(format, 'winPoints')) {
    const pts = [rules.winPoints, rules.drawPoints, rules.lossPoints, rules.walkoverWinnerPoints];
    if (pts.some(p => !Number.isFinite(p) || p < 0)) {
      issues.push({ field: 'winPoints', message: t('mode.err.negativePoints') });
    }
  }

  // --- draws, in every mode --------------------------------------------------
  if (spec.draws.policy === 'requires-resolution' && rules.allowDraws) {
    // A level match cannot advance anybody, so the organizer has to say what
    // settles it. Without a rule the app refuses the result, so we say so here
    // instead of letting them find out at match time.
    if ((rules.drawResolution ?? 'none') === 'none') {
      issues.push({ field: 'drawResolution', message: t('mode.err.drawNeedsRule') });
    } else if (rules.drawResolution === 'overtime' && !rules.overtimeAllowed) {
      issues.push({ field: 'overtimeAllowed', message: t('mode.err.overtimeNeeded') });
    }
  }

  // --- tie-breaks, where a table decides the order ----------------------------
  if (showsField(format, 'tiebreakOrder') && rules.tiebreakOrder.length === 0) {
    issues.push({ field: 'tiebreakOrder', message: t('mode.err.noTiebreak') });
  }

  if (format === 'groups-knockout') {
    const plan = groupPlan(rules, n);
    if ((rules.groupCount ?? 2) < 2) issues.push({ field: 'groupCount', message: t('mode.err.groupsMin') });
    if ((rules.advancePerGroup ?? 2) < 1) issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceMin') });
    if (n) {
      const groups = Math.max(2, Math.floor(rules.groupCount ?? 2));
      const advance = Math.max(1, Math.floor(rules.advancePerGroup ?? 2));
      if (groups > n || plan.smallest < 2) {
        issues.push({ field: 'groupCount', message: t('mode.err.groupsTooMany', { groups, n }) });
      }
      // Someone has to stay behind in each group, or the group stage decides
      // nothing and the bracket is not a qualification at all.
      if (advance >= plan.smallest) {
        issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceTooMany', { advance, perGroup: plan.smallest }) });
      }
      if (groups * advance < 2) {
        issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceNoBracket') });
      }
    }
  }

  if (format === 'swiss') {
    const rounds = rules.swissRounds ?? 5;
    if (rounds < 1) issues.push({ field: 'swissRounds', message: t('mode.err.roundsMin') });
    if (n && rounds > n - 1) {
      issues.push({ field: 'swissRounds', message: t('mode.err.roundsTooMany', { rounds, max: n - 1 }) });
    }
  }

  // Settings the mode shows but the generator cannot act on are named in the
  // settings panel and in the mode explanation. They are deliberately NOT an
  // issue here: Custom always has some, so an issue would make a custom event
  // impossible to create.

  // --- a custom event has to state its stage ----------------------------------
  // The one thing a custom format may not leave to the app: what it is built
  // from. An ungenerated stage is refused by name rather than quietly ignored.
  if (format === 'custom') {
    const stage = rules.customStage;
    if (!stage) {
      issues.push({ field: 'customStage', message: t('mode.err.stageRequired') });
    } else if (!GENERATED_CUSTOM_STAGES.includes(stage)) {
      issues.push({ field: 'customStage', message: t('mode.err.stageNotBuilt', { stage: t(`mode.stageName.${stage}` as never) }) });
    }
  }
  if ((format === 'round-robin' || format === 'team-match' || format === 'individual-match')
      && n && choose2(n) * (rules.homeAway ? 2 : 1) > 400) {
    issues.push({ field: 'homeAway', message: t('mode.err.tooManyMatches', { n }) });
  }

  if (format === 'league' && n && n < 3) {
    issues.push({ field: 'format', message: t('mode.err.leagueTooSmall', { n }) });
  }

  return issues;
}

// ---- which settings a mode actually shows -----------------------------------

/**
 * The RuleSet fields behind each setting group. This map is the only place that
 * decides visibility, so the wizard, the rules screen and the tests cannot drift
 * apart: a format lists groups, a group lists fields, and a field is shown
 * exactly when its group is listed.
 */
export const SETTING_FIELDS: Record<SettingGroup, readonly (keyof RuleSet)[]> = {
  // Points for a result — the engine of every table-producing format.
  scoring: ['winPoints', 'drawPoints', 'lossPoints', 'walkoverWinnerPoints'],
  // Whether a match may end level, and what settles it when it does.
  draws: ['allowDraws', 'drawResolution'],
  // How equal points are separated.
  tiebreak: ['tiebreakOrder'],
  // Who plays whom, and whether extra time exists.
  seeding: ['seeding', 'overtimeAllowed'],
  // Group count and who advances.
  groups: ['groupCount', 'advancePerGroup'],
  // How many Swiss rounds.
  rounds: ['swissRounds'],
  // Home & away.
  meeting: ['homeAway'],
  // Points a free pass is worth.
  byes: ['byePoints'],
  // Points that exist only for reports and exports. They never decide anything.
  reporting: ['winPoints', 'drawPoints', 'lossPoints', 'walkoverWinnerPoints'],
  // The stage a custom event is built from. Only Custom has this.
  structure: ['customStage'],
};

/** Every group, in the order the setup screens list them. */
export const ALL_GROUPS: readonly SettingGroup[] = [
  'scoring', 'draws', 'tiebreak', 'seeding', 'groups', 'rounds', 'meeting', 'byes',
  'structure', 'reporting',
];

// ---- the rule layer: what each setting does *in this mode* ----------------

/** How much a setting matters in a given mode. */
export type SettingStatus = 'required' | 'optional' | 'advanced' | 'reporting';
/** What changing a setting actually changes. */
export type ScoreEffect = 'progression' | 'ranking' | 'tie-break' | 'reporting' | 'none';
/** Whether a level match can stand, and what settles it when it cannot. */
export type DrawPolicy = 'not-allowed' | 'allowed' | 'requires-resolution';
/** What decides who goes forward, or who ranks first. */
export type Advancement = 'bracket' | 'table' | 'rounds' | 'fixtures';

export interface FieldRule {
  field: keyof RuleSet;
  group: SettingGroup;
  status: SettingStatus;
  affects: ScoreEffect;
  /** One line saying what this field does — in plain words, no jargon. */
  why: keyof Dict;
}

export interface ModeSpec {
  format: CompetitionFormat;
  info: ModeInfo;
  /** Setting groups this mode shows, in screen order. */
  groups: readonly SettingGroup[];
  /** Every field it shows, classified. Anything missing is not applicable. */
  fields: readonly FieldRule[];
  /** 2. The stages this mode is allowed to have, in the order they run. */
  stages: readonly StageSpec[];
  /** 3-6. The same fields grouped by what they are to the organizer. */
  points: { status: SettingStatus; affects: ScoreEffect; why: keyof Dict };
  draws: { policy: DrawPolicy; why: keyof Dict; resolutions: readonly DrawResolution[] };
  groupSize: { status: SettingStatus; why: keyof Dict };
  advancement: { kind: Advancement; why: keyof Dict };
  /** 11. How equal points are separated — or that there is no order here. */
  tiebreak: { applies: boolean; why: keyof Dict };
  /** 12. What an export or a printed sheet contains, and what it leaves out. */
  reporting: { produces: keyof Dict; omits: keyof Dict };
  /** 13. The odd cases this mode actually has, named one by one. */
  edgeCases: readonly (keyof Dict)[];
  /** What is explicitly not available here, so nothing is left implied. */
  unsupported: readonly (keyof Dict)[];
  structure: { contains: keyof Dict; excludes: keyof Dict };
}

/** One stage of a mode: what it is, what it makes, how people move through it. */
export interface StageSpec {
  key: keyof Dict;
  /** What this stage produces. */
  produces: keyof Dict;
  /** How a participant leaves the stage and reaches the next one. */
  flow: keyof Dict;
}

type ModeClass = 'bracket' | 'table' | 'rounds' | 'hybrid' | 'fixtures';

const CLASS_OF: Record<CompetitionFormat, ModeClass> = {
  'single-elimination': 'bracket',
  'double-elimination': 'bracket',
  'round-robin': 'table',
  league: 'table',
  'team-match': 'table',
  'individual-match': 'table',
  swiss: 'rounds',
  'groups-knockout': 'hybrid',
  custom: 'fixtures',
};

interface Role { status: SettingStatus; affects: ScoreEffect }
const REPORTING: Role = { status: 'reporting', affects: 'reporting' };

/**
 * The rule table. A format shows exactly the fields listed for its class; every
 * other field is not applicable to it and is never rendered. The class is a
 * statement of intent, not a UI grouping: two formats in the same class share
 * their mechanics, so they share their rules.
 */
const ROLES: Record<ModeClass, Partial<Record<keyof RuleSet, Role>>> = {
  // A bracket is decided by the match result. Points exist for the paperwork.
  bracket: {
    seeding: { status: 'required', affects: 'progression' },
    overtimeAllowed: { status: 'optional', affects: 'progression' },
    allowDraws: { status: 'advanced', affects: 'progression' },
    drawResolution: { status: 'advanced', affects: 'progression' },
    winPoints: REPORTING, drawPoints: REPORTING, lossPoints: REPORTING, walkoverWinnerPoints: REPORTING,
  },
  // A table is the result: points build it, tie-breaks order it.
  table: {
    winPoints: { status: 'required', affects: 'ranking' },
    drawPoints: { status: 'required', affects: 'ranking' },
    lossPoints: { status: 'required', affects: 'ranking' },
    walkoverWinnerPoints: { status: 'optional', affects: 'ranking' },
    allowDraws: { status: 'required', affects: 'ranking' },
    tiebreakOrder: { status: 'required', affects: 'tie-break' },
    seeding: { status: 'optional', affects: 'ranking' },
    // genRoundRobin really does build a second half from this.
    homeAway: { status: 'optional', affects: 'progression' },
    overtimeAllowed: { status: 'advanced', affects: 'progression' },
  },
  // Swiss: points drive both the pairing and the ranking.
  rounds: {
    winPoints: { status: 'required', affects: 'ranking' },
    drawPoints: { status: 'required', affects: 'ranking' },
    lossPoints: { status: 'required', affects: 'ranking' },
    allowDraws: { status: 'required', affects: 'ranking' },
    tiebreakOrder: { status: 'required', affects: 'tie-break' },
    swissRounds: { status: 'required', affects: 'progression' },
    byePoints: { status: 'optional', affects: 'ranking' },
  },
  // Two stages: the group table decides, the bracket finishes it.
  hybrid: {
    winPoints: { status: 'required', affects: 'ranking' },
    drawPoints: { status: 'required', affects: 'ranking' },
    lossPoints: { status: 'required', affects: 'ranking' },
    walkoverWinnerPoints: { status: 'optional', affects: 'ranking' },
    allowDraws: { status: 'required', affects: 'ranking' },
    tiebreakOrder: { status: 'required', affects: 'tie-break' },
    seeding: { status: 'required', affects: 'progression' },
    groupCount: { status: 'required', affects: 'progression' },
    advancePerGroup: { status: 'required', affects: 'progression' },
    overtimeAllowed: { status: 'advanced', affects: 'progression' },
  },
  // Custom: every combination is on show, and the ones the generator cannot
  // build are labelled as such instead of pretending to work.
  fixtures: {
    winPoints: { status: 'optional', affects: 'ranking' },
    drawPoints: { status: 'optional', affects: 'ranking' },
    lossPoints: { status: 'optional', affects: 'ranking' },
    walkoverWinnerPoints: { status: 'optional', affects: 'ranking' },
    allowDraws: { status: 'optional', affects: 'ranking' },
    drawResolution: { status: 'advanced', affects: 'none' },
    tiebreakOrder: { status: 'optional', affects: 'tie-break' },
    seeding: { status: 'optional', affects: 'progression' },
    groupCount: { status: 'advanced', affects: 'none' },
    advancePerGroup: { status: 'advanced', affects: 'none' },
    swissRounds: { status: 'advanced', affects: 'none' },
    // The flat list is generated by genRoundRobin, which reads homeAway.
    homeAway: { status: 'optional', affects: 'progression' },
    byePoints: { status: 'optional', affects: 'ranking' },
    overtimeAllowed: { status: 'advanced', affects: 'progression' },
    // The stage the organizer states. Only the pairing list is generated today;
    // the validation refuses the rest by name rather than ignoring them.
    customStage: { status: 'required', affects: 'progression' },
  },
};

/** What each field does, in one line. Shared: the nuance is in status/affects. */
const WHY: Record<keyof RuleSet, keyof Dict> = {
  rounds: 'mode.why.rounds',
  matchLengthMin: 'mode.why.matchLength',
  winPoints: 'mode.why.winPoints',
  drawPoints: 'mode.why.drawPoints',
  lossPoints: 'mode.why.lossPoints',
  allowDraws: 'mode.why.allowDraws',
  drawResolution: 'mode.why.drawResolution',
  tiebreakOrder: 'mode.why.tiebreakOrder',
  walkoverWinnerPoints: 'mode.why.walkoverPoints',
  overtimeAllowed: 'mode.why.overtime',
  seeding: 'mode.why.seeding',
  groupCount: 'mode.why.groupCount',
  advancePerGroup: 'mode.why.advancePerGroup',
  homeAway: 'mode.why.homeAway',
  swissRounds: 'mode.why.swissRounds',
  byePoints: 'mode.why.byePoints',
  customStage: 'mode.why.customStage',
};

/**
 * The label a field is shown under. Not every field has a "rules.*" key, so a
 * message that names fields cannot build the name by string: three of them live
 * under a different prefix, and a missing key would print itself in the UI.
 */
const FIELD_LABELS: Record<keyof RuleSet, keyof Dict> = {
  rounds: 'rules.swissRounds',
  matchLengthMin: 'mode.why.matchLength',
  winPoints: 'rules.win',
  drawPoints: 'rules.draw',
  lossPoints: 'rules.loss',
  allowDraws: 'rules.allowDraws',
  drawResolution: 'mode.rules.drawRule',
  tiebreakOrder: 'rules.tiebreak',
  walkoverWinnerPoints: 'rules.walkoverWin',
  overtimeAllowed: 'rules.overtime',
  seeding: 'rules.seeding',
  groupCount: 'common.groups',
  advancePerGroup: 'rules.advance',
  homeAway: 'rules.homeAway',
  swissRounds: 'rules.swissRounds',
  byePoints: 'rules.byePoints',
  customStage: 'rules.customStage',
};

/** The user-facing name of a rule field, in the active language. */
export function labelOfField(field: keyof RuleSet): string {
  return t(FIELD_LABELS[field]);
}

/** Every rule field the app knows, so "not applicable" can name the rest. */
export const ALL_RULE_FIELDS: readonly (keyof RuleSet)[] =
  Object.keys(WHY) as (keyof RuleSet)[];

const POINTS_STMT: Record<ModeClass, ModeSpec['points']> = {
  bracket: { status: 'reporting', affects: 'reporting', why: 'mode.points.bracket' },
  table: { status: 'required', affects: 'ranking', why: 'mode.points.table' },
  rounds: { status: 'required', affects: 'ranking', why: 'mode.points.rounds' },
  hybrid: { status: 'required', affects: 'ranking', why: 'mode.points.hybrid' },
  fixtures: { status: 'optional', affects: 'ranking', why: 'mode.points.fixtures' },
};

const DRAW_STMT: Record<ModeClass, ModeSpec['draws']> = {
  bracket: {
    policy: 'requires-resolution', resolutions: ['overtime', 'replay', 'penalty', 'tiebreak'],
    why: 'mode.draws.bracket',
  },
  table: { policy: 'allowed', resolutions: [], why: 'mode.draws.table' },
  rounds: { policy: 'allowed', resolutions: [], why: 'mode.draws.rounds' },
  hybrid: { policy: 'allowed', resolutions: [], why: 'mode.draws.hybrid' },
  fixtures: { policy: 'allowed', resolutions: [], why: 'mode.draws.fixtures' },
};

const GROUP_SIZE_STMT: Record<ModeClass, ModeSpec['groupSize']> = {
  bracket: { status: 'reporting', why: 'mode.groupSize.bracket' },
  table: { status: 'optional', why: 'mode.groupSize.table' },
  rounds: { status: 'reporting', why: 'mode.groupSize.rounds' },
  hybrid: { status: 'required', why: 'mode.groupSize.hybrid' },
  fixtures: { status: 'advanced', why: 'mode.groupSize.fixtures' },
};

const ADVANCE_STMT: Record<ModeClass, ModeSpec['advancement']> = {
  bracket: { kind: 'bracket', why: 'mode.adv.bracket' },
  table: { kind: 'table', why: 'mode.adv.table' },
  rounds: { kind: 'rounds', why: 'mode.adv.rounds' },
  hybrid: { kind: 'bracket', why: 'mode.adv.hybrid' },
  fixtures: { kind: 'fixtures', why: 'mode.adv.fixtures' },
};

const CONTAINS: Record<ModeClass, keyof Dict> = {
  bracket: 'mode.contains.bracket',
  table: 'mode.contains.table',
  rounds: 'mode.contains.rounds',
  hybrid: 'mode.contains.hybrid',
  fixtures: 'mode.contains.fixtures',
};

const EXCLUDES: Record<ModeClass, keyof Dict> = {
  bracket: 'mode.excludes.bracket',
  table: 'mode.excludes.table',
  rounds: 'mode.excludes.rounds',
  hybrid: 'mode.excludes.hybrid',
  fixtures: 'mode.excludes.fixtures',
};


// ---- the stages a mode is allowed to have ----------------------------------

const S = (
  key: keyof Dict, produces: keyof Dict, flow: keyof Dict,
): StageSpec => ({ key, produces, flow });

const BRACKET_STAGES: readonly StageSpec[] = [
  S('mode.stage.bracket', 'mode.stage.bracket.produces', 'mode.stage.bracket.flow'),
];

const DOUBLE_STAGES: readonly StageSpec[] = [
  S('mode.stage.winners', 'mode.stage.winners.produces', 'mode.stage.winners.flow'),
  S('mode.stage.losers', 'mode.stage.losers.produces', 'mode.stage.losers.flow'),
  S('mode.stage.grandFinal', 'mode.stage.grandFinal.produces', 'mode.stage.grandFinal.flow'),
];

const GROUP_STAGES: readonly StageSpec[] = [
  S('mode.stage.groups', 'mode.stage.groups.produces', 'mode.stage.groups.flow'),
  S('mode.stage.knockout', 'mode.stage.knockout.produces', 'mode.stage.knockout.flow'),
];

const PAIRING_STAGES: readonly StageSpec[] = [
  S('mode.stage.pairings', 'mode.stage.pairings.produces', 'mode.stage.pairings.flow'),
];

const SEASON_STAGES: readonly StageSpec[] = [
  S('mode.stage.season', 'mode.stage.season.produces', 'mode.stage.season.flow'),
];

const SWISS_STAGES: readonly StageSpec[] = [
  S('mode.stage.round1', 'mode.stage.round1.produces', 'mode.stage.round1.flow'),
  S('mode.stage.laterRounds', 'mode.stage.laterRounds.produces', 'mode.stage.laterRounds.flow'),
];

const CUSTOM_STAGES: readonly StageSpec[] = [
  S('mode.stage.pairings', 'mode.stage.pairings.produces', 'mode.stage.custom.flow'),
];

/** Per format, because the stages are a property of the format, not of a class. */
const STAGES: Record<CompetitionFormat, readonly StageSpec[]> = {
  'single-elimination': BRACKET_STAGES,
  'double-elimination': DOUBLE_STAGES,
  'groups-knockout': GROUP_STAGES,
  'round-robin': PAIRING_STAGES,
  league: SEASON_STAGES,
  swiss: SWISS_STAGES,
  'team-match': PAIRING_STAGES,
  'individual-match': PAIRING_STAGES,
  custom: CUSTOM_STAGES,
};

const TIEBREAK_STMT: Record<ModeClass, ModeSpec['tiebreak']> = {
  bracket: { applies: false, why: 'mode.tiebreak.bracket' },
  table: { applies: true, why: 'mode.tiebreak.table' },
  rounds: { applies: true, why: 'mode.tiebreak.rounds' },
  hybrid: { applies: true, why: 'mode.tiebreak.hybrid' },
  fixtures: { applies: true, why: 'mode.tiebreak.fixtures' },
};

const REPORTING_STMT: Record<ModeClass, ModeSpec['reporting']> = {
  bracket: { produces: 'mode.reporting.bracket', omits: 'mode.reporting.bracketOmits' },
  table: { produces: 'mode.reporting.table', omits: 'mode.reporting.tableOmits' },
  rounds: { produces: 'mode.reporting.rounds', omits: 'mode.reporting.roundsOmits' },
  hybrid: { produces: 'mode.reporting.hybrid', omits: 'mode.reporting.hybridOmits' },
  fixtures: { produces: 'mode.reporting.fixtures', omits: 'mode.reporting.fixturesOmits' },
};

const EDGE_CASES: Record<ModeClass, readonly (keyof Dict)[]> = {
  bracket: ['mode.edge.byes', 'mode.edge.unresolved', 'mode.edge.twoParticipants'],
  table: ['mode.edge.byes', 'mode.edge.allDraws', 'mode.edge.twoParticipants'],
  rounds: ['mode.edge.byes', 'mode.edge.noRepeat', 'mode.edge.oddPoints'],
  hybrid: ['mode.edge.byes', 'mode.edge.unevenGroups', 'mode.edge.knockoutByes', 'mode.edge.unresolved'],
  fixtures: ['mode.edge.byes', 'mode.edge.homeAway', 'mode.edge.twoParticipants'],
};

/**
 * What is deliberately not available in a mode. Named, so a feature that is not
 * offered can never be mistaken for one that was forgotten.
 */
const UNSUPPORTED: Record<ModeClass, readonly (keyof Dict)[]> = {
  bracket: ['mode.no.thirdPlace', 'mode.no.divisions', 'mode.no.wildcards'],
  table: ['mode.no.thirdPlace', 'mode.no.divisions', 'mode.no.wildcards'],
  rounds: ['mode.no.thirdPlace', 'mode.no.divisions', 'mode.no.wildcards', 'mode.no.cut'],
  hybrid: ['mode.no.thirdPlace', 'mode.no.divisions'],
  fixtures: ['mode.no.multiStage', 'mode.no.thirdPlace', 'mode.no.divisions', 'mode.no.wildcards'],
};

function buildSpec(m: ModeInfo): ModeSpec {
  const cls = CLASS_OF[m.format];
  const roles = ROLES[cls];
  const groups = ALL_GROUPS.filter(g => (m.settings as readonly SettingGroup[]).includes(g));
  const fields: FieldRule[] = [];
  for (const g of groups) {
    for (const f of SETTING_FIELDS[g]) {
      const role = roles[f];
      // No role means the field is not applicable to this mode: it is never
      // rendered, not greyed out and not hidden behind "advanced".
      if (!role || fields.some(x => x.field === f)) continue;
      // Two statuses override the shared sentence, because the shared one is
      // written for the mode where the setting actually does the work.
      const why = role.status === 'reporting' ? 'mode.why.reporting'
        : (role.affects === 'none' && role.status === 'advanced') ? 'mode.why.inert'
          : WHY[f];
      fields.push({ field: f, group: g, status: role.status, affects: role.affects, why });
    }
  }
  return {
    format: m.format,
    info: m,
    groups,
    fields,
    stages: STAGES[m.format],
    points: POINTS_STMT[cls],
    draws: DRAW_STMT[cls],
    groupSize: GROUP_SIZE_STMT[cls],
    advancement: ADVANCE_STMT[cls],
    tiebreak: TIEBREAK_STMT[cls],
    reporting: REPORTING_STMT[cls],
    edgeCases: EDGE_CASES[cls],
    unsupported: UNSUPPORTED[cls],
    structure: { contains: CONTAINS[cls], excludes: EXCLUDES[cls] },
  };
}

/** The fields a mode shows, split by what they are to the organizer. */
export function fieldsByStatus(format: string, status: SettingStatus): FieldRule[] {
  return specFor(format).fields.filter(f => f.status === status);
}

/** Every RuleSet field that does not apply to this mode at all. */
export function notApplicableFields(format: string): (keyof RuleSet)[] {
  const shown = new Set(specFor(format).fields.map(f => f.field));
  return ALL_RULE_FIELDS.filter(f => !shown.has(f));
}

/** The fields a mode requires; the ones it validates before it can generate. */
export function requiredFields(format: string): FieldRule[] {
  return fieldsByStatus(format, 'required');
}

const SPECS = new Map<CompetitionFormat, ModeSpec>(MODES.map(m => [m.format, buildSpec(m)]));

/** The full rule set of a format. Unknown formats read as Custom. */
export function specFor(format: string): ModeSpec {
  return SPECS.get(format as CompetitionFormat) ?? SPECS.get('custom')!;
}

/** How one field behaves in this mode, or null when it does not apply. */
export function fieldRule(format: string, field: keyof RuleSet): FieldRule | null {
  return specFor(format).fields.find(f => f.field === field) ?? null;
}

/** The classification of a field, or 'not-applicable' when it is hidden. */
export function fieldStatus(format: string, field: keyof RuleSet): SettingStatus | 'not-applicable' {
  return fieldRule(format, field)?.status ?? 'not-applicable';
}

/** What the field changes here: progression, ranking, tie-break, reporting, nothing. */
export function fieldEffect(format: string, field: keyof RuleSet): ScoreEffect {
  return fieldRule(format, field)?.affects ?? 'none';
}

/**
 * The rules that have to change when the organizer changes the format.
 *
 * Only the draw rule is touched, because that is the one thing the format itself
 * decides: a bracket cannot advance on a level match, a table can. Points,
 * tie-breaks and the rest are left exactly as they are — the organizer set those
 * on purpose, and switching format is not a reason to overwrite them.
 */
export function adaptRulesToFormat(format: string, rules: RuleSet): Partial<RuleSet> {
  const spec = specFor(format);
  if (spec.draws.policy === 'requires-resolution') {
    // A bracket starts closed: no draws until a rule to settle them is chosen.
    return { allowDraws: false, drawResolution: 'none' };
  }
  // Every other format treats a draw as a normal result.
  return { allowDraws: true, drawResolution: 'none' };
}

/**
 * The fields a mode may actually show as controls: everything it has a rule for
 * except the ones its generator never reads. A field with no effect is not a
 * control — it is a sentence in the mode note.
 */
export function renderableFields(format: string): FieldRule[] {
  return specFor(format).fields.filter(f => f.affects !== 'none');
}

/** The fields a mode has, but that change nothing in it. */
export function inertFields(format: string): FieldRule[] {
  return specFor(format).fields.filter(f => f.affects === 'none');
}

/**
 * The groups a format renders, in screen order. A group whose every field is
 * inert renders nothing at all, so no panel is left standing empty.
 */
export function visibleGroups(format: string): SettingGroup[] {
  const spec = specFor(format);
  const live = new Set(renderableFields(format).map(f => f.group));
  return spec.groups.filter(g => live.has(g));
}

/** The groups a format hides — the screen explains why instead of leaving a gap. */
export function hiddenGroups(format: string): SettingGroup[] {
  const shown = new Set(visibleGroups(format));
  return ALL_GROUPS.filter(g => !shown.has(g));
}

/** Every RuleSet field a format shows, classified in mode-specs order. */
export function visibleFields(format: string): (keyof RuleSet)[] {
  return specFor(format).fields.map(f => f.field);
}

/** True when this field applies to this format at all. */
export function showsField(format: string, field: keyof RuleSet): boolean {
  return fieldRule(format, field) !== null;
}

// ---- group sizes -----------------------------------------------------------

export interface GroupPlan {
  groups: number;
  /** Participants per group, biggest first as produced by the remainder split. */
  sizes: number[];
  smallest: number;
  largest: number;
  /** True when the count does not divide evenly — allowed, and explained. */
  uneven: boolean;
  qualifiers: number;
  knockoutSize: number;
  knockoutByes: number;
}

/**
 * How the field is dealt into groups and what that leaves for the knockout.
 *
 * Sizes come out as even as the count allows: the remainder is spread one
 * participant at a time, so a field of 10 in 4 groups becomes 3/3/2/2 rather
 * than 4/2/2/2. The generator deals participants in blocks, which also spreads
 * the strong and the weak across different groups. Uneven groups are a normal
 * outcome, not a mistake, and the screen says so instead of hiding the number.
 */
export function groupPlan(rules: RuleSet, participantCount?: number | null): GroupPlan {
  const real = typeof participantCount === 'number' && participantCount >= 2;
  const count = real ? Math.floor(participantCount) : PREVIEW_SAMPLE;
  const groups = Math.max(2, Math.floor(rules.groupCount ?? 2));
  const advance = Math.max(1, Math.floor(rules.advancePerGroup ?? 2));
  const base = Math.floor(count / groups);
  const extra = count % groups;
  const sizes = Array.from({ length: groups }, (_, i) => base + (i < extra ? 1 : 0));
  const qualifiers = groups * advance;
  const knockoutSize = pow2(qualifiers);
  return {
    groups,
    sizes,
    smallest: sizes.length ? Math.min(...sizes) : 0,
    largest: sizes.length ? Math.max(...sizes) : 0,
    uneven: extra > 0,
    qualifiers,
    knockoutSize,
    knockoutByes: Math.max(0, knockoutSize - qualifiers),
  };
}

// ---- picker grouping --------------------------------------------------------

export type PickerGroup = ModeInfo['group'];

export const PICKER_GROUPS: readonly PickerGroup[] = ['quick', 'ranking', 'groups', 'other'];

const GROUP_TITLES: Record<PickerGroup, keyof Dict> = {
  quick: 'mode.groupQuick',
  ranking: 'mode.groupRanking',
  groups: 'mode.groupGroups',
  other: 'mode.groupOther',
};

export function pickerGroupTitle(group: PickerGroup): keyof Dict {
  return GROUP_TITLES[group];
}

/** The modes for a picker group, in catalogue order. */
export function modesInGroup(group: PickerGroup): ModeInfo[] {
  return MODES.filter((m) => m.group === group);
}

// ---- the confirmation summary ----------------------------------------------

export interface SummaryLine { key: keyof Dict; value: string }

/**
 * The rules that actually apply, as short lines — the "before you create it"
 * block. Only visible groups produce a line, so a bracket never claims to score
 * points and a league never claims to have rounds.
 */
export function summaryRows(
  format: string,
  rules: RuleSet,
  participantCount?: number | null,
): SummaryLine[] {
  const rows: SummaryLine[] = [];
  const spec = specFor(format);
  const has = (g: SettingGroup) => visibleGroups(format).includes(g);
  const resolution = rules.drawResolution ?? 'none';

  // The one line that says what this format actually is.
  rows.push({ key: 'mode.sum.advances', value: t(spec.advancement.why) });

  if (has('seeding')) {
    rows.push({ key: 'mode.sum.seeding', value: t(`rules.seeding.${rules.seeding}` as never) });
  }
  if (has('scoring')) {
    rows.push({
      key: 'mode.sum.points',
      value: t('mode.sum.pointsValue', { win: rules.winPoints, draw: rules.drawPoints, loss: rules.lossPoints }),
    });
  }
  if (has('reporting')) {
    // Points in a bracket: present, named, and explicitly powerless.
    rows.push({
      key: 'mode.sum.reporting',
      value: t('mode.sum.reportingValue', { win: rules.winPoints, draw: rules.drawPoints, loss: rules.lossPoints }),
    });
  }
  if (has('draws')) {
    if (spec.draws.policy === 'requires-resolution') {
      rows.push({
        key: 'mode.sum.drawRule',
        value: rules.allowDraws ? t(`mode.resolution.${resolution}` as never) : t('mode.draws.notAllowed'),
      });
    } else {
      rows.push({ key: 'mode.sum.draws', value: rules.allowDraws ? t('common.yes') : t('common.no') });
    }
  }
  if (has('tiebreak')) {
    const names = rules.tiebreakOrder.slice(0, 2)
      .map((k) => t(`rules.tiebreak.${k}` as never))
      .join(' \u2192 ');
    rows.push({ key: 'mode.sum.tiebreak', value: names || t('common.tbd') });
  }
  if (has('groups')) {
    const plan = groupPlan(rules, participantCount);
    rows.push({
      key: 'mode.sum.groupPlan',
      value: t('mode.sum.groupPlanValue', {
        sizes: plan.sizes.join(' / '), advance: rules.advancePerGroup ?? 2,
      }),
    });
  }
  if (has('rounds')) {
    rows.push({ key: 'mode.sum.rounds', value: t('mode.sum.roundsValue', { rounds: rules.swissRounds ?? 5 }) });
  }
  if (has('meeting')) {
    rows.push({ key: 'mode.sum.meeting', value: rules.homeAway ? t('preview.twice') : t('preview.once') });
  }
  if (has('byes')) {
    rows.push({ key: 'mode.sum.bye', value: t('mode.sum.byeValue', { points: rules.byePoints ?? 3 }) });
  }
  if (showsField(format, 'overtimeAllowed') && rules.overtimeAllowed) {
    rows.push({ key: 'mode.sum.overtime', value: t('common.yes') });
  }
  return rows;
}

/**
 * Glossary entries worth showing for a format - the terms that appear in this
 * mode's explanation or preview, and nowhere else. A league has no bracket, so
 * it is not offered the word.
 */
export function glossaryFor(format: string): (keyof Dict)[] {
  const mode = modeOf(format);
  const groups = visibleGroups(format);
  const terms: (keyof Dict)[] = ['mode.term.advancement'];
  if (mode.bracket) terms.push('mode.term.bracket', 'mode.term.bye');
  if (format === 'double-elimination') terms.push('mode.term.doubleElim', 'mode.term.draw');
  if (groups.includes('seeding')) terms.push('mode.term.seeding');
  if (groups.includes('tiebreak')) terms.push('mode.term.tiebreak');
  if (groups.includes('groups')) terms.push('mode.term.groupStage', 'mode.term.qualifier');
  if (format === 'league' || format === 'round-robin') terms.push('mode.term.matchday', 'mode.term.roundRobin');
  if (format === 'swiss') terms.push('mode.term.scoreGroup', 'mode.term.swiss');
  if (mode.settings.includes('reporting')) terms.push('mode.term.reportingOnly');
  return terms;
}
