// What each tournament mode means, which settings it actually needs, and what
// the app will generate for a given field size.
//
// This is the single source of truth behind the setup screens: the mode picker,
// the explanations, the presets, the visible settings and the preview all read
// from here, so a format can never be described one way and generated another.
// Pure and deterministic — no DOM, no randomness, no tournament state.
import { t, type Dict } from '../i18n';
import { CompetitionFormat, Match, Participant, RuleSet, ValidationIssueLike } from './types';
import { genSingleElim } from './elim';
import { genDoubleElim } from './double';
import { genGroupsKnockout, genLeague, genRoundRobin } from './generate';
import { swissPairings } from './swiss';

export type SettingGroup =
  | 'scoring'      // points per result
  | 'tiebreak'     // how equal points are separated
  | 'seeding'      // who plays whom in the first round
  | 'groups'       // group count and who advances
  | 'rounds'       // how many Swiss rounds
  | 'meeting'      // home & away
  | 'byes';        // free pass points for an odd field

export interface ModeInfo {
  format: CompetitionFormat;
  /** Where the mode lives in the picker — by intent, not by feature name. */
  group: 'quick' | 'ranking' | 'groups' | 'other';
  /** One-line meaning, plain language, no jargon. */
  meaning: keyof Dict;
  /** A concrete, checkable example: "8 players → …". */
  example: keyof Dict;
  goodFor: keyof Dict;
  notIncluded: keyof Dict;
  /** Setting groups this mode genuinely needs; anything else is not shown. */
  settings: readonly SettingGroup[];
  /** Points are part of the result here (a table is produced). */
  points: boolean;
  /** The event ends in a knockout bracket. */
  bracket: boolean;
  /** The whole fixture list is generated in one go. */
  autoGenerated: boolean;
}

/**
 * The catalogue. Order inside each group is the order the picker shows.
 *
 * `points` and `bracket` are the same facts the engine uses to decide whether a
 * ranking table or a bracket makes sense — see hasPointTable()/hasBracket().
 */
export const MODES: readonly ModeInfo[] = [
  {
    format: 'single-elimination', group: 'quick',
    meaning: 'format.meaning.single-elimination',
    example: 'format.example.single-elimination',
    goodFor: 'format.for.single-elimination',
    notIncluded: 'format.not.single-elimination',
    settings: ['seeding'],
    points: false, bracket: true, autoGenerated: true,
  },
  {
    format: 'double-elimination', group: 'quick',
    meaning: 'format.meaning.double-elimination',
    example: 'format.example.double-elimination',
    goodFor: 'format.for.double-elimination',
    notIncluded: 'format.not.double-elimination',
    settings: ['seeding'],
    points: false, bracket: true, autoGenerated: true,
  },
  {
    format: 'groups-knockout', group: 'groups',
    meaning: 'format.meaning.groups-knockout',
    example: 'format.example.groups-knockout',
    goodFor: 'format.for.groups-knockout',
    notIncluded: 'format.not.groups-knockout',
    settings: ['scoring', 'tiebreak', 'seeding', 'groups'],
    points: true, bracket: true, autoGenerated: true,
  },
  {
    format: 'round-robin', group: 'ranking',
    meaning: 'format.meaning.round-robin',
    example: 'format.example.round-robin',
    goodFor: 'format.for.round-robin',
    notIncluded: 'format.not.round-robin',
    settings: ['scoring', 'tiebreak', 'seeding', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'swiss', group: 'ranking',
    meaning: 'format.meaning.swiss',
    example: 'format.example.swiss',
    goodFor: 'format.for.swiss',
    notIncluded: 'format.not.swiss',
    settings: ['scoring', 'tiebreak', 'rounds', 'byes'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'league', group: 'ranking',
    meaning: 'format.meaning.league',
    example: 'format.example.league',
    goodFor: 'format.for.league',
    notIncluded: 'format.not.league',
    settings: ['scoring', 'tiebreak', 'seeding', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'team-match', group: 'other',
    meaning: 'format.meaning.team-match',
    example: 'format.example.team-match',
    goodFor: 'format.for.team-match',
    notIncluded: 'format.not.team-match',
    settings: ['scoring', 'tiebreak', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'individual-match', group: 'other',
    meaning: 'format.meaning.individual-match',
    example: 'format.example.individual-match',
    goodFor: 'format.for.individual-match',
    notIncluded: 'format.not.individual-match',
    settings: ['scoring', 'tiebreak', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
  {
    format: 'custom', group: 'other',
    meaning: 'format.meaning.custom',
    example: 'format.example.custom',
    goodFor: 'format.for.custom',
    notIncluded: 'format.not.custom',
    settings: ['scoring', 'tiebreak', 'seeding', 'meeting'],
    points: true, bracket: false, autoGenerated: true,
  },
];

const BY_FORMAT = new Map<CompetitionFormat, ModeInfo>(MODES.map((m) => [m.format, m]));

/** The catalogue entry for a format; anything unknown is treated as Custom. */
export function modeOf(format: string): ModeInfo {
  return BY_FORMAT.get(format as CompetitionFormat) ?? modeOf('custom');
}

/** Only these setting groups are shown for a format — the rest stay hidden. */
export function settingGroupsFor(format: string): readonly SettingGroup[] {
  return modeOf(format).settings;
}

// ---- what the app will generate --------------------------------------------

export interface PreviewRow { key: keyof Dict; value: string }

export interface StructurePreview {
  format: CompetitionFormat;
  /** Which kind of output the organizer gets. */
  kind: 'bracket' | 'table' | 'groups' | 'rounds' | 'fixtures';
  titleKey: keyof Dict;
  rows: PreviewRow[];
  notes: (keyof Dict)[];
  /** Matches that exist as soon as the organizer presses generate. */
  matches: number | null;
  /** Matches that only appear later — the next Swiss round, the knockout. */
  later: number;
  /** Free passes the plan contains. A bye is a slot, not a match to play. */
  byes: number;
  /** The field size the numbers were computed for. */
  count: number;
  /** True when the numbers come from a sample, not a real participant count. */
  assumed: boolean;
}

/** Field size used for the preview when the organizer has not said. */
export const PREVIEW_SAMPLE = 8;

function pow2(n: number): number {
  let r = 1;
  while (r < n) r *= 2;
  return r;
}
const choose2 = (n: number) => (n * (n - 1)) / 2;

/** Rounds a round robin needs: one per opponent, plus one when someone sits out. */
function rrRounds(n: number): number {
  return n % 2 === 1 ? n : n - 1;
}

function syntheticField(count: number): Participant[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `preview_${i}`,
    name: `P${i + 1}`,
    kind: 'player' as const,
    active: true,
    seed: i + 1,
    tags: [],
  }));
}

/**
 * What the real generator would create for a field of this size — counted, not
 * estimated, by running it on a synthetic field. Seeding is forced to the input
 * order so the count is deterministic; the order of the pairings never changes
 * how many matches there are.
 *
 * Byes are counted apart: the app stores a free pass as a match row, but nobody
 * plays it, and a preview that counted it would overstate the work.
 */
function planned(format: string, count: number, rules: RuleSet): { played: number; byes: number } {
  const ps = syntheticField(count);
  const r: RuleSet = { ...rules, seeding: 'seeded' };
  const all: Match[] =
    format === 'single-elimination' ? genSingleElim(ps, r).matches
      : format === 'double-elimination' ? genDoubleElim(ps, r).matches
        : format === 'league' ? genLeague(ps, r)
          : format === 'groups-knockout' ? genGroupsKnockout(ps, r).matches
            : format === 'swiss' ? swissPairings(ps, [], new Map(ps.map(p => [p.id, 0])), 1)
              : genRoundRobin(ps, r);
  // A free pass is a row with one participant and no opponent. A row with two
  // empty slots is not a bye at all — it is a later round waiting for a result,
  // and it still belongs to the total the organizer will play.
  const byes = all.filter(m => (m.homeId === null) !== (m.awayId === null)).length;
  return { played: all.length - byes, byes };
}

/**
 * Describes the output for a format at a given field size, so the setup screens
 * can show it live and tests can hold it against the generators.
 */
export function previewStructure(
  format: string,
  participantCount: number | null | undefined,
  rules: RuleSet,
): StructurePreview {
  const mode = modeOf(format);
  const real = typeof participantCount === 'number' && participantCount >= 2;
  const count = real ? Math.floor(participantCount) : PREVIEW_SAMPLE;
  const rows: PreviewRow[] = [];
  const notes: (keyof Dict)[] = [];
  let kind: StructurePreview['kind'] = 'bracket';
  let matches: number | null = null;
  let later = 0;
  let byes = 0;
  const push = (key: keyof Dict, value: string | number) => rows.push({ key, value: String(value) });
  const byeRows = () => { if (byes > 0) push('preview.byes', byes); };

  switch (format) {
    case 'single-elimination': {
      const size = pow2(count);
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.rounds', Math.log2(size));
      push('preview.matches', matches);
      byeRows();
      if (size > count) notes.push('preview.noteByes');
      push('preview.ends', t('preview.endsFinal'));
      break;
    }
    case 'double-elimination': {
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.winnersLosers', t('preview.wlCount', { n: Math.max(0, matches - 1) }));
      push('preview.grandFinal', 1);
      push('preview.matches', matches);
      byeRows();
      notes.push('preview.noteReset');
      break;
    }
    case 'round-robin':
    case 'team-match':
    case 'individual-match':
    case 'custom': {
      kind = format === 'custom' ? 'fixtures' : 'table';
      ({ played: matches, byes } = planned(format, count, rules));
      push('preview.rounds', rrRounds(count));
      push('preview.matches', matches);
      byeRows();
      if (byes > 0) notes.push('preview.noteRRBye');
      push('preview.meetings', rules.homeAway ? t('preview.twice') : t('preview.once'));
      push('preview.ends', t('preview.endsTable'));
      if (format === 'custom') notes.push('preview.noteCustom');
      break;
    }
    case 'league': {
      kind = 'table';
      ({ played: matches, byes } = planned(format, count, rules));
      const double = rules.homeAway ?? true;
      push('preview.matchdays', rrRounds(count) * (double ? 2 : 1));
      push('preview.matches', matches);
      byeRows();
      if (byes > 0) notes.push('preview.noteRRBye');
      push('preview.meetings', double ? t('preview.twice') : t('preview.once'));
      push('preview.ends', t('preview.endsTable'));
      break;
    }
    case 'swiss': {
      // Only the first round exists after generating; the rest are paired from
      // the standings, round by round, as results come in.
      kind = 'rounds';
      const plannedRounds = Math.max(1, rules.swissRounds ?? 5);
      const first = planned(format, count, rules);
      matches = first.played;
      byes = first.byes;
      const perRound = first.played + first.byes;
      later = (plannedRounds - 1) * perRound;
      push('preview.roundsPlanned', plannedRounds);
      push('preview.matchesPerRound', perRound);
      push('preview.matchesTotal', perRound * plannedRounds);
      notes.push('preview.noteSwiss');
      if (byes > 0) notes.push('preview.noteSwissBye');
      break;
    }
    case 'groups-knockout': {
      // The group stage is generated now; the bracket is built from the
      // qualifiers once the groups are finished.
      kind = 'groups';
      const groups = Math.max(2, rules.groupCount ?? 2);
      const advance = Math.max(1, rules.advancePerGroup ?? 2);
      const base = Math.floor(count / groups);
      const extra = count % groups;
      const sizes = Array.from({ length: groups }, (_, i) => base + (i < extra ? 1 : 0));
      ({ played: matches, byes } = planned(format, count, rules));
      const qualifiers = groups * advance;
      const koSize = pow2(qualifiers);
      push('preview.groups', groups);
      push('preview.groupSizes', sizes.join(' / '));
      push('preview.groupMatches', matches);
      byeRows();
      push('preview.qualifiers', qualifiers);
      later = Math.max(0, qualifiers - 1);
      push('preview.koMatches', later);
      if (koSize > qualifiers) push('preview.koByes', koSize - qualifiers);
      notes.push('preview.noteGroupsKo');
      break;
    }
    default:
      kind = 'bracket';
  }

  return {
    format: mode.format,
    kind,
    titleKey: mode.points && !mode.bracket ? 'preview.titleTable' : 'preview.titleStructure',
    rows,
    notes,
    matches,
    later,
    byes,
    count,
    assumed: !real,
  };
}

// ---- does this combination of rules make sense? ----------------------------

/**
 * Rule combinations that are legal but almost certainly not what the organizer
 * meant. The same shape the engine's validation uses, so the setup screens and
 * `validateTournament` share it. Pure: it only reads rules and field size.
 */
export function validateModeSetup(
  format: string,
  rules: RuleSet,
  participantCount?: number | null,
): ValidationIssueLike[] {
  const issues: ValidationIssueLike[] = [];
  const n = typeof participantCount === 'number' && participantCount >= 2
    ? Math.floor(participantCount)
    : null;

  if (format === 'groups-knockout') {
    const groups = rules.groupCount ?? 2;
    const advance = rules.advancePerGroup ?? 2;
    if (groups < 2) issues.push({ field: 'groupCount', message: t('mode.err.groupsMin') });
    if (advance < 1) issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceMin') });
    if (n) {
      const perGroup = Math.floor(n / groups);
      if (groups > n || perGroup < 2) {
        issues.push({ field: 'groupCount', message: t('mode.err.groupsTooMany', { groups, n }) });
      }
      if (advance >= perGroup) {
        issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceTooMany', { advance, perGroup }) });
      }
      if (groups * advance < 2) {
        issues.push({ field: 'advancePerGroup', message: t('mode.err.advanceNoBracket') });
      }
    }
  }

  if (format === 'swiss') {
    const rounds = rules.swissRounds ?? 5;
    if (rounds < 1) issues.push({ field: 'swissRounds', message: t('mode.err.roundsMin') });
    if (n && rounds > n - 1) {
      issues.push({ field: 'swissRounds', message: t('mode.err.roundsTooMany', { rounds, max: n - 1 }) });
    }
  }

  if ((format === 'round-robin' || format === 'team-match' || format === 'individual-match')
      && n && choose2(n) * (rules.homeAway ? 2 : 1) > 400) {
    issues.push({ field: 'homeAway', message: t('mode.err.tooManyMatches', { n }) });
  }

  if (format === 'league' && n && n < 3) {
    issues.push({ field: 'format', message: t('mode.err.leagueTooSmall', { n }) });
  }

  return issues;
}

// ---- which settings a mode actually shows -----------------------------------

/**
 * The RuleSet fields behind each setting group. This map is the only place that
 * decides visibility, so the wizard, the rules screen and the tests cannot drift
 * apart: a format lists groups, a group lists fields, and a field is shown
 * exactly when its group is listed.
 */
export const SETTING_FIELDS: Record<SettingGroup, readonly (keyof RuleSet)[]> = {
  // Who plays whom, and how a match is settled before it is played.
  seeding: ['seeding', 'allowDraws', 'overtimeAllowed'],
  // Points for a result — only where a table is actually produced.
  scoring: ['winPoints', 'drawPoints', 'lossPoints', 'walkoverWinnerPoints', 'allowDraws'],
  // How equal points are separated.
  tiebreak: ['tiebreakOrder'],
  // Group count and who advances.
  groups: ['groupCount', 'advancePerGroup'],
  // How many Swiss rounds.
  rounds: ['swissRounds'],
  // Home & away.
  meeting: ['homeAway'],
  // Points a free pass is worth.
  byes: ['byePoints'],
};

/** Every group, in the order the setup screens list them. */
export const ALL_GROUPS: readonly SettingGroup[] = [
  'scoring', 'tiebreak', 'seeding', 'groups', 'rounds', 'meeting', 'byes',
];

/** The groups a format shows, in catalogue order. */
export function visibleGroups(format: string): SettingGroup[] {
  const shown = new Set(modeOf(format).settings);
  return ALL_GROUPS.filter((g) => shown.has(g));
}

/** The groups a format hides — the screen explains why instead of leaving a gap. */
export function hiddenGroups(format: string): SettingGroup[] {
  const shown = new Set(modeOf(format).settings);
  return ALL_GROUPS.filter((g) => !shown.has(g));
}

/** Every RuleSet field a format shows, de-duplicated and in catalogue order. */
export function visibleFields(format: string): (keyof RuleSet)[] {
  const out: (keyof RuleSet)[] = [];
  for (const g of visibleGroups(format)) {
    for (const f of SETTING_FIELDS[g]) if (!out.includes(f)) out.push(f);
  }
  return out;
}

/** True when this format shows this field. Bracket modes never show points. */
export function showsField(format: string, field: keyof RuleSet): boolean {
  return visibleFields(format).includes(field);
}

// ---- picker grouping --------------------------------------------------------

export type PickerGroup = ModeInfo['group'];

export const PICKER_GROUPS: readonly PickerGroup[] = ['quick', 'ranking', 'groups', 'other'];

const GROUP_TITLES: Record<PickerGroup, keyof Dict> = {
  quick: 'mode.groupQuick',
  ranking: 'mode.groupRanking',
  groups: 'mode.groupGroups',
  other: 'mode.groupOther',
};

export function pickerGroupTitle(group: PickerGroup): keyof Dict {
  return GROUP_TITLES[group];
}

/** The modes for a picker group, in catalogue order. */
export function modesInGroup(group: PickerGroup): ModeInfo[] {
  return MODES.filter((m) => m.group === group);
}

// ---- the confirmation summary ----------------------------------------------

export interface SummaryLine { key: keyof Dict; value: string }

/**
 * The rules that actually apply, as short lines — the "before you create it"
 * block. Only visible groups produce a line, so a bracket never claims to score
 * points and a league never claims to have rounds.
 */
export function summaryRows(format: string, rules: RuleSet): SummaryLine[] {
  const rows: SummaryLine[] = [];
  const has = (g: SettingGroup) => visibleGroups(format).includes(g);
  const group = ALL_GROUPS.filter(has);

  if (has('seeding')) {
    rows.push({ key: 'mode.sum.seeding', value: t(`rules.seeding.${rules.seeding}` as never) });
  }
  if (has('scoring')) {
    rows.push({ key: 'mode.sum.points', value: t('mode.sum.pointsValue', { win: rules.winPoints, draw: rules.drawPoints, loss: rules.lossPoints }) });
    if (!rules.allowDraws) rows.push({ key: 'mode.sum.draws', value: t('common.no') });
  }
  if (rules.allowDraws && has('scoring') && !has('seeding')) {
    rows.push({ key: 'mode.sum.draws', value: t('common.yes') });
  }
  if (has('tiebreak')) {
    const names = rules.tiebreakOrder.slice(0, 2)
      .map((k) => t(`rules.tiebreak.${k}` as never))
      .join(' \u2192 ');
    rows.push({ key: 'mode.sum.tiebreak', value: names });
  }
  if (has('groups')) {
    rows.push({ key: 'mode.sum.groups', value: t('mode.sum.groupsValue', { groups: rules.groupCount ?? 2, advance: rules.advancePerGroup ?? 2 }) });
  }
  if (has('rounds')) {
    rows.push({ key: 'mode.sum.rounds', value: t('mode.sum.roundsValue', { rounds: rules.swissRounds ?? 5 }) });
  }
  if (has('meeting')) {
    rows.push({ key: 'mode.sum.meeting', value: rules.homeAway ? t('preview.twice') : t('preview.once') });
  }
  if (has('byes')) {
    rows.push({ key: 'mode.sum.bye', value: t('mode.sum.byeValue', { points: rules.byePoints ?? 3 }) });
  }
  if (has('seeding') && rules.overtimeAllowed) {
    rows.push({ key: 'mode.sum.overtime', value: t('common.yes') });
  }
  return rows;
}

/**
 * Glossary entries worth showing for a format - the terms that appear in this
 * mode's explanation or preview, and nowhere else. A league has no bracket, so
 * it is not offered the word.
 */
export function glossaryFor(format: string): (keyof Dict)[] {
  const mode = modeOf(format);
  const groups = visibleGroups(format);
  const terms: (keyof Dict)[] = [];
  if (mode.bracket) terms.push('mode.term.bracket', 'mode.term.bye');
  if (groups.includes('seeding')) terms.push('mode.term.seeding');
  if (groups.includes('tiebreak')) terms.push('mode.term.tiebreak');
  if (groups.includes('groups')) terms.push('mode.term.groupStage', 'mode.term.qualifier');
  if (format === 'league' || format === 'round-robin') terms.push('mode.term.matchday');
  if (format === 'swiss') terms.push('mode.term.scoreGroup');
  if (format === 'double-elimination') terms.push('mode.term.doubleElim');
  return terms;
}
